### ISSUE TITLE
 0.25 degree JRA55 RYF 'Quick Start' instructions

### ISSUE THREAD

**Issue by ruth-moorman** [COSIMA/access-om2#111]
I followed the Quick Start instructions on the wiki for running the 0.25 degree JRA55 RYF experiment and it's currently not self contained as you end up missing mppnccombine and the compiling stage doesn't go through.

**Comment by nicjhan** [comment]
Thanks @ruth-moorman, we're just in the process of updating the documentation. Did you get it going? If not perhaps you could try out the updated instructions in a couple of days.

**Comment by aekiss** [comment]
I'm guessing we can close this now? https://github.com/COSIMA/access-om2/wiki/Getting-started#quick-start has been updated and seems to work.
