### ISSUE TITLE
document impact of payu ice restart bug

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#123]
Copying from [slack](https://arccss.slack.com/archives/C6PP0GU9Y/p1542768035080900):

Payu had a bug in handling ice restarts which has since been fixed: https://github.com/marshallward/payu/issues/138

We should document its impact on existing runs: 
- which payu versions were affected?
- is this only for YATM-based runs?
- is it only for IAF or RYF also?
- what incorrect coupling fields are used on the first timestep? (how incorrect are they?)

**Comment by aidanheerdegen** [comment]
A single timestep? Minimal I'd have thought. In other words, a worthy goal, but not sure there are resources to look into it, unless it is critical to the paper.

**Comment by aekiss** [comment]
It's not just a single timestep. It affects all of the first JRA55 or CORE forcing period (3 hours or 6 hours, respectively

**Comment by aidanheerdegen** [comment]
Ok, these are steps identified in the TWG meeting to remedy this issue

1. Confirm payu/0.11.2 working correctly
2. Set as default version
3. Determine which payu versions affected
4. Turn off affected modules in modulefile and issue message about bug, what module to load and to email climate_help if users still has issues
5. When complain assess individual cases
6. If necessary move payu module to non-app path
7. Delete old versions?

**Comment by aidanheerdegen** [comment]
Can we get as many people as possible using `payu/0.11.2`? Ping @AndyHoggANU @navidcy @angus-g 

I'll tell Taimoor and Ruth

**Comment by navidcy** [comment]
I was using it but there was bugs and switched back to v0.10. Shall I go back to latest?

**Comment by aidanheerdegen** [comment]
Are these all the affected versions?

```
/apps/payu/0.7/lib/payu/models/accessom2.py
/apps/payu/0.8.1/lib/payu/models/accessom2.py
/apps/payu/0.8/lib/payu/models/accessom2.py
/apps/payu/0.9.1/lib/payu/models/accessom2.py
/apps/payu/0.9.2/lib/payu/models/accessom2.py
/apps/payu/0.9/lib/payu/models/accessom2.py
/apps/payu/0.10/lib/payu/models/accessom2.py
/apps/payu/0.11/lib/python3.6/site-packages/payu-0.11-py3.6.egg/payu/models/accessom2.py
/apps/payu/0.11.1/lib/python3.6/site-packages/payu-0.11.1-py3.6.egg/payu/models/accessom2.py
/apps/payu/0.11.2/lib/python3.6/site-packages/payu-0.11.2-py3.6.egg/payu/models/accessom2.py
```

**Comment by aidanheerdegen** [comment]
> I was using it but there was bugs and switched back to v0.10. Shall I go back to latest?

Yes please. We tracked down the issue with `0.11.2` and it should work now. You aren't affected by the bug we're talking about, but we may need to deactivate old versions, so would like to make sure other users aren't affected.

**Comment by AndyHoggANU** [comment]
Yes, I will switch over ... but can we ensure that the config.yaml in Nic's default config uses syntax for 0.11.2? I had trouble with the syntax change on 0.10 and still haven't quite figured it out.

**Comment by aekiss** [comment]
The spreadsheets in `/g/data3/hh5/tmp/cosima/access-om2-run-summaries` tabulate the payu version used for each run, so we can determine exactly what was affected.

For the record, this bug affected the entire 0.1 deg IAF run `01deg_jra55v13_iaf` in the model announcement paper and runs 414 onwards in the RYF spinup `01deg_jra55v13_ryf8485_spinup6` that formed its initial condition. The 1 deg and 0.25 deg runs in the paper were not affected.

**Comment by aekiss** [comment]
Buggy pre-0.11.2 versions of payu are still available:
```
module avail payu

----------------------------------------------------------------- /projects/v45/modules -----------------------------------------------------------------
payu/aek  payu/dev  payu/test

--------------------------------------------------------------- /apps/Modules/modulefiles ---------------------------------------------------------------
payu/0.10   payu/0.11.1 payu/0.11.2 payu/0.7    payu/0.8    payu/0.8.1  payu/0.9    payu/0.9.1  payu/0.9.2
```

Is there any reason not to disable these (see point 4 above)?

**Comment by aekiss** [comment]
Buggy pre-0.11.2 versions of payu are still available - is there any reason not to disable these as disussed?

**Comment by aidanheerdegen** [comment]
I have deactivated all the `payu` modules in `projects/v45`, but I don't have permissions do anything with the system modules. I doubt @marshallward does either now.

**Comment by marshallward** [comment]
I still have /apps permission, will be available in about an hour

**Comment by navidcy** [comment]
Wow. They cancelled Marshall’s door card at 4:59 last day he was employed but they still allow him apps permissions. :)

**Comment by marshallward** [comment]
Questionable access permissions aside... I've done a 1.0 tag and installed it on Raijin.  It's not yet enabled as default, which is still set to 0.11.2.

I've also disabled 0.9-0.11.1 at the request of @aekiss since it lacks YATM support and sounds like there were some other dangerous bugs.

We can make 1.0 the default once people are comfortable using it.  I guess some announcement should be made somehow.

**Comment by aekiss** [comment]
OK thanks @marshallward

**Comment by aekiss** [comment]
It says [here](https://github.com/COSIMA/access-om2/issues/123#issuecomment-446038596) that test runs are underway to assess impact of this bug. Can anyone remember who was doing this and what was found? If not, should we close this issue? It has been noted in the [tech report](https://github.com/COSIMA/ACCESS-OM2-1-025-010deg-report) and the buggy payu versions are no longer available.
