### ISSUE TITLE
neutral density diagnostic levels for access-om2-01

### ISSUE THREAD

**Issue by russfiedler** [COSIMA/access-om2#135]
While doing some optimisation work I noted that the choice of levels for remapping to neutral density (actually potential density reffed to 2000m) hardly overlaps with the actual values.

`NEUTRALRHO_MIN  =   1020.00000000000     ,
 NEUTRALRHO_MAX  =   1030.00000000000     ,`

but if you look at plots of `pot_rho_2` you'll see that most values are way outside this range.

You end up with some very sparse plots for `ty_trans_nrho_submeso`! I haven't looked but it may well be an issue for other configs which look at things on neutral density surfaces.

I note that in GFDL's CM2.5 they have 
`
&ocean_density_nml
        potrho_min=1028.0
        potrho_max=1038.0
        neutralrho_min=1028.0
        neutralrho_max=1038.0
        layer_nk=80
        eos_linear=.false.
        eos_preteos10=.true.
`

**Comment by ofa001** [comment]
I have only looked at these diagnostics in the coupled model, so I am not sure if this holds there Russ, still ill at home so will have to check better when I am back in the office when I have the bigger screen to open more windows on! Could do it on the laptop but harder!

Siobhan

**Comment by aekiss** [comment]
I've set `neutralrho_min=1028.0` and `neutralrho_max=1038.0` for default all configurations  at 1, 0.25 and 0.1 deg (currently in `ak-dev` branch but will be merged into master).

Can this issue now be closed?

**Comment by russfiedler** [comment]
Yes, that should be good.

**Comment by aekiss** [comment]
A note to clarify Russ' comment above

> neutral density (actually potential density reffed to 2000m)

this is because `neutral_density_potrho` takes the default value true, and `potrho_press` takes the default value 2000.0
 
https://github.com/mom-ocean/MOM5/blob/99168b44ab45f4f5b4fa2544a0c3f644f0afb666/src/mom5/ocean_core/ocean_density.F90#L251-L257
