### ISSUE TITLE
use relative winds in CICE

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#138]
We are using relative winds to calculate surface fluxes over water but absolute winds over ice.

I think we should set `highfreq`=true in CICE namelist group `forcing_nml` to use relative winds for both (at present we aren't specifying it, and it defaults to false).

See https://github.com/OceansAus/access-om2/issues/137

**Comment by aekiss** [comment]
Relative winds may also reduce CFL problems with runaway ice since stress reduces as ice accelerates.

**Comment by ofa001** [comment]
Yes but that would change how the set up has been formulated. 

Looks like the scaling approach you have used has been successful, so perhaps this has solved the problem for now.

**Comment by aekiss** [comment]
Closing this issue.
I've set CICE to use relative wind (`highfreq=true`) in all default configurations at 1, 0.25 and 0.1 deg (currently in ak-dev branch but will be merged into master).
