### ISSUE TITLE
1deg and 0.25deg KDS50 bathymetry inherits terraces from GFDL50

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#141]
See below for a scatter plot of partial cell thickness versus full cell thickness in the three configurations used in the paper. The upper and lower lines have slopes of 1 and 0.2, respectively.
The scatter shows how model bottom cell thickness ranges between the full cell thickness and 20% of that (with a 10m minimum at 0.1deg discussed [here](https://github.com/OceansAus/access-om2/issues/99#issuecomment-414922491)).

I'm posting this issue to note the gaps in the 1deg and 0.25deg distributions.

The 1deg and 0.25deg topog.nc files use the KDS50 vertical grid but were based on files generated for the GFDL50 grid, which already had a (presumably 20%) minimum partial cell thickness. When adapted to KDS50 the GFDL50 minimum cell thickness produces gaps in the thickness distribution, i.e. the small terraces produced by the GFDL minimum partial cell thickness are inherited by the topography on the KDS50 vertical grid. At least, that's what I think is going on. 

If we wanted to fix this we'd need to go back to a more raw topography file, before the minimum-thickness threshold was applied.

![partialcells](https://user-images.githubusercontent.com/31054815/55699711-724a6c00-5a0f-11e9-8fbd-97e9180253d4.png)
(plot script is [here](https://github.com/OceansAus/ACCESS-OM2-1-025-010deg-report/blob/master/figures/bathymetry/bathymetry.ipynb))

**Comment by russfiedler** [comment]
"If we wanted to fix this we'd need to go back to a more raw topography file, before the minimum-thickness threshold was applied."

Russ Fiedler hides...

More seriously, yes, I think you've got that right. There should be gaps between 0-20% of the original grid, which would manifest itself as a slope of 0.2 in the original GM50. In other words there is no topography with values between `zw(k)` and `zw(k)+0.2*(zw(k+2)-zw(k))` 

Nice presentation of the result. I like the `Nike` tick mark in the 025 example!

**Comment by aekiss** [comment]
Closing - this has been fixed in `/g/data/ik11/inputs/access-om2/input_20201022/` - see https://github.com/COSIMA/access-om2/issues/158#issuecomment-698758041
