### ISSUE TITLE
Exact, time-averaged heat content diagnostics missing

### ISSUE THREAD

**Issue by rmholmes** [COSIMA/access-om2#142]
For all the runs in the documentation paper, we are saving monthly averages of `temp` and `dzt`. However the exact, spatially-resolved, time-averaged heat content cannot be reproduced exactly from these because of missing correlations between the two. The missing 3D diagnostic is `temp_rhodzt`. Of course, errors are likely small (I'm not sure how small...).

For future runs, can we please add the 2D diagnostic `temp_int_rhodz`? As we are saving all of the vertically-integrated heat fluxes and the surface heat flux, this should allow exact closure of the vertically-integrated heat budget.

**Comment by rmholmes** [comment]
Oh wait, we still could not close the budget exactly without saving snapshots (of which we have some in the restarts). I think the 2D diagnostic would still be useful though.

**Comment by rmholmes** [comment]
Just adding to this with another request: It looks like `dzt` is saved only annually, not monthly in most of the runs. I would suggest saving monthly-averages of `dzt`.

**Comment by aekiss** [comment]
OK I'll make `dzt` monthly in the new configs. 
Is `temp_int_rhodz` the right name? It [doesn't show up in a search](https://github.com/mom-ocean/MOM5/search?q=temp_int_rhodz) but I guess it's one of those programmatically-generated names. And I guess you'd like that monthly too?

**Comment by rmholmes** [comment]
`temp_int_rhodz` is indeed the name (https://github.com/rmholmes/MOM5/blob/master/src/mom5/ocean_tracers/ocean_tracer.F90#L1211-L1216). It's a 2D field so monthly would be great (and it'd make it super easy to plot vertically-integrated heat content anomalies). Thanks.

**Comment by russfiedler** [comment]
`dzt` can always be calculated exactly from knowledge of `eta_t` so doesn't need to be stored. You need the time invariant fields `depth`, `dstlo` and `dstup`. The latter 2 are in all `ocean_thickness.res.nc` restarts.  We do this for BRAN. In fact you only need the sum of `dstlo` and `dstup` for this calculation so you could have that saved once.

**Comment by rmholmes** [comment]
Fair enough. I've never done that calculation but I'm sure it's easy enough. That would save a 3D variable at the cost of a bit more faffing for analysis.

**Comment by russfiedler** [comment]
Yeah, I've got the Fortran code. Just a few lines the calculation is pretty simple and quick. Once you get the 3D array for `dstlo + dstup` loaded it should fly through. Have a look at `/scratch/v45/raf599/restarts/make_restart_thick_tripolar_decomp.f90` for one version. Lines 64 and  129 do the work.

**Comment by aekiss** [comment]
@rmholmes I've added monthly `temp_int_rhodz` and `dzt` to the new defaults but let me know if you want me to remove `dzt`.

**Comment by rmholmes** [comment]
You can remove `dzt`.

**Comment by aekiss** [comment]
@russfiedler, @rmholmes we are storing `sea_level`, not `eta_t`. These are the same with the current configuration (`max_ice_thickness=0`) but if that changes they'll differ, which will complicate the  calculation of `dzt` under ice. I guess we'll worry about that if/when it happens.

**Comment by russfiedler** [comment]
`eta_t` can always be added if that happens and we can probably calculate it pretty accurately from the ice mass if that is saved at the same frequency.
