### ISSUE TITLE
namelist error

### ISSUE THREAD

**Issue by keweilyu** [COSIMA/access-om2#145]
Hello, I've been getting these errors (attached) --- All I did is just modifying config.yaml to simply run 1deg_jra55_ryf. I didn't have this problem before until last Friday, when I decided to remove everything and download and re-build model.  

[access-om2.out.txt](https://github.com/COSIMA/access-om2/files/3146179/access-om2.out.txt)
[access-om2.err.txt](https://github.com/COSIMA/access-om2/files/3146180/access-om2.err.txt)

**Comment by aekiss** [comment]
Hi thanks for letting me know - I updated things on Friday and may have broken something. Looks like cice is unable to read a namelist. Can you tell me the directory on NCI you're running this from so I can have a closer look?

**Comment by keweilyu** [comment]
Thanks, Andrew. Here is the folder,

/short/fp2/kxl599/access-om2/control/1deg_jra55_ryf

--
Kewei Lyu | Postdoctoral Fellow

Centre for Southern Hemisphere Oceans Research
CSIRO Oceans & Atmosphere
GPO Box 1538, Hobart, TAS 7001

**Comment by aekiss** [comment]
Thanks but unfortunately I don't have read access to /short/fp2

You shouldn't need to re-build (ie re-compile) the model. If you just do
`git clone https://github.com/COSIMA/1deg_jra55_ryf.git`
that should be ready to run. See https://github.com/COSIMA/access-om2/wiki/Getting-started#quick-start
Is this what you did? If so it might be worth trying again, as I did two commits on Friday and you might have got the old one: https://github.com/COSIMA/1deg_jra55_ryf/commits/master

Also what did you mean by "modifying config.yaml to simply run 1deg_jra55_ryf"?

**Comment by keweilyu** [comment]
Thanks Andrew. Actually I download and build the whole model as I will need to look into the details and modify code. Sorry for confusion --- I only edit config.yaml to set the project and shortpath. I'll have another try now.

**Comment by russfiedler** [comment]
Hi,

I've suggested that some debugging code be added. That error message is mostly useless. They have the error code returned by the failing read but don't put it in the error message. Duh!

Russ
________________________________

**Comment by russfiedler** [comment]
I just downloaded everything and ran the 1 deg ryf case. The only thing I changed was some diag_tables the run time (6 hours) and general configs and got the same error for the namelist. Something is definitely broken. My guess is that changing the time broke something but it could be something else.

Does the CICE namelist go through some sort of`sed` script? A whole lot of commas are removed but it looks like npt has been converted to a real whereas it should be an integer. This corresponds to the error code  In the repository version the cice_in.nml file looks like

&setup_nml
    days_per_year  = 365
  , use_leap_years = .false.
  , year_init      = 0001
  , istep0         = 0
  , dt             = 3600
  , npt            = 35040   INTEGER

but in the work directory


&setup_nml
    days_per_year = 365
    use_leap_years = .false.
    year_init = 1
    istep0 = 0
    dt = 3600
    npt = 35040.0   FLOAT

Is this a problem with payu or something else? Should a different version be used?

**Comment by russfiedler** [comment]
Actually, that wasn't the error.  You can read in a real but I think it's still an error on `payu`'s part to write something like that.

Still hunting...

**Comment by russfiedler** [comment]
Ok found the problem

In the namelist file there is a logical variable `lcdf64` but this doesn't appear in the `setup_nml` namelist in the code.

This variable was removed by @nichannah  stuffing up existing namelists

https://github.com/COSIMA/cice5/commit/d2ef6b1a15929ae5933b1724f671c5b94432a20a#diff-ad0de16fa7f0dbc37accca5aa3b94191

**Comment by aekiss** [comment]
Thanks for tracking this down @russfiedler. So this bit us again because I updated the CICE exes in the 1 deg configs. I'll fix the cice_in.nml files in the control github repos.

@keweilyu if you remove  the line containing `lcdf64` from the `cice_in.nml` file it should fix the problem.

**Comment by keweilyu** [comment]
Thanks @russfiedler and @aekiss for your help. I have removed lcdf64 from the cice_in.nml file and it works.

**Comment by aekiss** [comment]
great!
