### ISSUE TITLE
namelists have pottemp_equal_contemp=.true. causing SST problems

### ISSUE THREAD

**Issue by russfiedler** [COSIMA/access-om2#148]
Setting the conservative and potential temperatures to be the same is not a good thing. It doesn't matter so much in simulations with `PT` as the prognostic temperature but if you have `CT` as the temperature you may end up passing the wrong temperature to the coupler.

See also

 https://github.com/mom-ocean/MOM5/issues/284

**Comment by aekiss** [comment]
I've removed `pottemp_equal_contemp` from `input.nml` so it defaults to false for all default configurations at 1, 0.25 and 0.1 deg (currently in ak-dev branch but will be merged into master).

Can this issue now be closed?

**Comment by aekiss** [comment]
![Screen Shot 2019-08-14 at Wed 14-8 8 57am](https://user-images.githubusercontent.com/31054815/62983108-93194700-be71-11e9-8e52-88d500304ef4.png)

Just for reference, here's the difference between potential and conservative temperature at the sea surface from p 98 of the [TEOS-10 manual](http://www.teos-10.org/pubs/TEOS-10_Manual.pdf).
