### ISSUE TITLE
unable to checkout 025deg_jra55_ryf

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/access-om2#152]
When I do "git clone --recursive https://github.com/COSIMA/access-om2.git", it says that it was unable to checkout 0.25 degree RYF configuration. Is this a known issue?

[hh0162@raijin4 short]$ git clone --recursive https://github.com/COSIMA/access-om2.git
Initialized empty Git repository in /short/v45/hh0162/access-om2/.git/
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 2008 (delta 46), reused 68 (delta 29), pack-reused 1914
Receiving objects: 100% (2008/2008), 730.07 KiB | 328 KiB/s, done.
Resolving deltas: 100% (1234/1234), done.
Submodule 'control/01deg_jra55_iaf' (https://github.com/COSIMA/01deg_jra55_iaf.git) registered for path 'control/01deg_jra55_iaf'
Submodule 'control/01deg_jra55_ryf' (https://github.com/COSIMA/01deg_jra55_ryf.git) registered for path 'control/01deg_jra55_ryf'
Submodule 'control/025deg_core2_nyf' (https://github.com/COSIMA/025deg_core2_nyf.git) registered for path 'control/025deg_core2_nyf'
Submodule 'control/025deg_jra55_iaf' (https://github.com/COSIMA/025deg_jra55_iaf.git) registered for path 'control/025deg_jra55_iaf'
Submodule 'control/025deg_jra55_ryf' (https://github.com/COSIMA/025deg_jra55_ryf.git) registered for path 'control/025deg_jra55_ryf'
Submodule 'control/1deg_core_nyf' (https://github.com/COSIMA/1deg_core_nyf.git) registered for path 'control/1deg_core_nyf'
Submodule 'control/1deg_jra55_iaf' (https://github.com/COSIMA/1deg_jra55_iaf.git) registered for path 'control/1deg_jra55_iaf'
Submodule 'control/1deg_jra55_ryf' (https://github.com/COSIMA/1deg_jra55_ryf.git) registered for path 'control/1deg_jra55_ryf'
Submodule 'control/minimal_01deg_jra55_iaf' (https://github.com/COSIMA/minimal_01deg_jra55_iaf.git) registered for path 'control/minimal_01deg_jra55_iaf'
Submodule 'control/minimal_01deg_jra55_ryf' (https://github.com/COSIMA/minimal_01deg_jra55_ryf.git) registered for path 'control/minimal_01deg_jra55_ryf'
Submodule 'src/cice5' (https://github.com/COSIMA/cice5.git) registered for path 'src/cice5'
Submodule 'src/libaccessom2' (https://github.com/COSIMA/libaccessom2.git) registered for path 'src/libaccessom2'
Submodule 'src/mom' (https://github.com/mom-ocean/MOM5.git) registered for path 'src/mom'
Submodule 'tools/esmgrids' (https://github.com/DoublePrecision/esmgrids.git) registered for path 'tools/esmgrids'
Initialized empty Git repository in /short/v45/hh0162/access-om2/control/01deg_jra55_iaf/.git/
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1218 (delta 8), reused 14 (delta 5), pack-reused 1198
Receiving objects: 100% (1218/1218), 149.74 KiB, done.
Resolving deltas: 100% (792/792), done.
Submodule path 'control/01deg_jra55_iaf': checked out '41bc773ff7ea5c7672a65d3e949c24e3f13083cc'
Initialized empty Git repository in /short/v45/hh0162/access-om2/control/01deg_jra55_ryf/.git/
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 998 (delta 1), reused 3 (delta 0), pack-reused 992
Receiving objects: 100% (998/998), 164.78 KiB, done.
Resolving deltas: 100% (638/638), done.
Submodule path 'control/01deg_jra55_ryf': checked out '5e4b0011dee2a81fa98b6a5ce8d32b3fa3a74799'
Initialized empty Git repository in /short/v45/hh0162/access-om2/control/025deg_core2_nyf/.git/
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 48 (delta 1), reused 4 (delta 1), pack-reused 39
Unpacking objects: 100% (48/48), done.
Submodule path 'control/025deg_core2_nyf': checked out '8e6a32b315dbdb7ec38062374e7a80c1f9e37404'
Initialized empty Git repository in /short/v45/hh0162/access-om2/control/025deg_jra55_iaf/.git/
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 378 (delta 10), reused 17 (delta 7), pack-reused 356
Receiving objects: 100% (378/378), 71.59 KiB, done.
Resolving deltas: 100% (212/212), done.
Submodule path 'control/025deg_jra55_iaf': checked out '31cac205c77928589d12f86c07ee61ebe1c06494'
Initialized empty Git repository in /short/v45/hh0162/access-om2/control/025deg_jra55_ryf/.git/
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 284 (delta 1), reused 2 (delta 0), pack-reused 277
Receiving objects: 100% (284/284), 49.17 KiB, done.
Resolving deltas: 100% (161/161), done.
fatal: reference is not a tree: 15f9bd0daebc8c6505f2c184128b963cd1934e57
Unable to checkout '15f9bd0daebc8c6505f2c184128b963cd1934e57' in submodule path 'control/025deg_jra55_ryf'
[hh0162@raijin4 short]$ rm -rf access-om2
[hh0162@raijin4 short]$ pwd
/home/581/hh0162/short
[hh0162@raijin4 short]$ git clone --recursive https://github.com/COSIMA/access-om2.git > ~/short/tmp/git_error.txt
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 2008 (delta 46), reused 68 (delta 29), pack-reused 1914
Receiving objects: 100% (2008/2008), 730.07 KiB | 340 KiB/s, done.
Resolving deltas: 100% (1234/1234), done.
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1218 (delta 8), reused 14 (delta 5), pack-reused 1198
Receiving objects: 100% (1218/1218), 149.74 KiB, done.
Resolving deltas: 100% (792/792), done.
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 998 (delta 1), reused 3 (delta 0), pack-reused 992
Receiving objects: 100% (998/998), 164.78 KiB, done.
Resolving deltas: 100% (638/638), done.
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 48 (delta 1), reused 4 (delta 1), pack-reused 39
Unpacking objects: 100% (48/48), done.
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 378 (delta 10), reused 17 (delta 7), pack-reused 356
Receiving objects: 100% (378/378), 71.59 KiB, done.
Resolving deltas: 100% (212/212), done.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 284 (delta 1), reused 2 (delta 0), pack-reused 277
Receiving objects: 100% (284/284), 49.17 KiB, done.
Resolving deltas: 100% (161/161), done.
fatal: reference is not a tree: 15f9bd0daebc8c6505f2c184128b963cd1934e57
Unable to checkout '15f9bd0daebc8c6505f2c184128b963cd1934e57' in submodule path 'control/025deg_jra55_ryf'

[git_error.txt](https://github.com/COSIMA/access-om2/files/3312362/git_error.txt)

**Comment by aekiss** [comment]
Thanks for flagging this @hakaseh.
@nichannah this appears to be due to your commit https://github.com/COSIMA/access-om2/commit/7ff327b#diff-695da1155a8d32c55c6f940298297a2f which sets `control/025deg_jra55_ryf` to commit 15f9bd0dae which doesn't exist - is there a local commit that needs to be pushed to github?

**Comment by aekiss** [comment]
@hakaseh - commit d25698517d03ab580a7768347d492277798647c4 resolves this issue

...however @nichannah is there anything from your commit 15f9bd0dae which should be merged in? If not, we can close this issue.

**Comment by hakaseh** [comment]
thanks @aekiss, i confirm that the commit resolves the issue.

**Comment by nichannah** [comment]
It looks like I didn't update to use the latest executable on this experiment. Thank you for fixing it @aekiss
