### ISSUE TITLE
use mppnccombine-fast in new standard configs?

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#154]
Am I right in thinking mppnccombine-fast is not quite ready to be used in the [default access-om2 configurations](https://github.com/COSIMA/access-om2/tree/master/control)?

There seem to be [a few remaining issues](https://github.com/coecms/mppnccombine-fast/issues), e.g. lack of compression in some instances.

**Comment by aidanheerdegen** [comment]
There is no point from a performance point of view with 1 degree configs (in general). 

Ryan recently had some issues with using it with output from a 0.25 model that had not used `io_layout`. The chunk sizes were very small, as they were based on small tile sizes, and that carried through to the collated files.

I'm now beginning to think we're better off *not* outputting compressed data, and do the compression in the collation step. With the option to collate restarts there is very little downside that I can seen.

**Comment by aekiss** [comment]
@aidanheerdegen Adele has found `mppnccombine-fast` is fine for her 0.1deg 1-month runs (https://arccss.slack.com/archives/C9Q7Y1400/p1587445015009200), so I'm thinking of using it for the new default configurations at all resolutions, instead of uncompressed output with compression in the collation step (https://github.com/COSIMA/access-om2/issues/168). Does that sound sensible?

**Comment by AndyHoggANU** [comment]
Sounds good to me! Will save a lot of hassle - and CPU time. And good to be consistent across configs.

**Comment by aidanheerdegen** [comment]
I don’t think it is worth changing for the 1 degree necessarily, and I believe the 0.25 needs testing because of inconsistent chunksize issues. It will most probably be ok, but will take longer and should really be tested to make sure.

Oh I see I was the one suggesting not compressing the outputs. Clearly I am very fickle.

**Comment by aekiss** [comment]
ok I'll use `mppnccombine-fast` for 0.1deg only at this stage.
At present there's no compression of MOM output at 1 deg or 0.25 deg - should I leave it that way? Hopefully the data won't be too overwhelming at those resolutions...

**Comment by aidanheerdegen** [comment]
Any idea how long is the 0.25deg taking to collate?

**Comment by aekiss** [comment]
The 0.25 tests I'm running take 4.5min to collate, and need 12.7Gb memory.
At 0.1 deg it's 15.5min and 75Gb.
This is without daily outputs at either resolution.

**Comment by aekiss** [comment]
That's with `deflate_level=5`

**Comment by aidanheerdegen** [comment]
Sorry, is this `mppnccombine-fast`?

**Comment by aekiss** [comment]
They're with `/g/data/ik11/inputs/access-om2/bin/mppnccombine` and these `diag_table`s:

0.25deg with 12-monthly 3d fields (4.5min and 12.7Gb)
https://github.com/COSIMA/025deg_jra55_ryf/blob/8948e6aa3bf60b3062a362ca68715b87f23f329d/ocean/diag_table

0.1 deg with 3-monthly 3-d output (15.5min and 75Gb): 
https://github.com/COSIMA/01deg_jra55_ryf/blob/b484ead114e0aeeaf20880f897cb852830b719f8/ocean/diag_table

The 0.1deg is quite quick due to the 3-monthly 3d output. With monthly output it's a little over 3x slower:

0.1 deg with monthly 3-d output (53min and 86Gb): 
https://github.com/COSIMA/01deg_jra55_iaf/blob/b05f9e35cd10756f93a64d556e8e0eb42dbdde3f/ocean/diag_table

**Comment by aekiss** [comment]
Closing. This has been done for the RYF and IAF configs at 0.1 deg and 0.25 deg on the ak-dev branch.
