### ISSUE TITLE
Fix up Rayleigh drag at 1 deg?

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#156]
There are some glitches in the Rayleigh drag locations specified at 1 deg in [ocean/field_table](https://github.com/COSIMA/1deg_jra55_iaf/blob/master/ocean/field_table). As shown below, damping was unintentionally omitted from the bottom 2 (3) U-cells in Lombok (Ombai) Strait and for 3/4 of the width of the Torres Strait.

I'm inclined to alter `field_table` to extend damping to all depths in Lombok and Ombai and across the full width of Torres Str. Any objections? Note that the Ombai and Lombok Str transports are already weak (see bottom plot).

![Screen Shot 2019-08-12 at Mon 12-8 3 11pm](https://user-images.githubusercontent.com/31054815/62846425-841c8280-bd13-11e9-88c9-96d56117b040.png)

Circles indicate where Rayleigh damping is defined in `ocean/field_table` and white cells are the U-grid land mask. Top: Rayleigh damping locations at 1deg (in the Lombok, Ombai and Torres Straits); colours in the circled cells indicate how many U-cells are not damped in each column. Bottom: Rayleigh damping timescale (or zero if not defined) at 1 deg. Where defined, damping timescales are all 5400 s. Figure script is [here](https://github.com/COSIMA/ACCESS-OM2-1-025-010deg-report/blob/master/figures/Rayleigh_drag/Rayleigh_drag.ipynb).

![Screen Shot 2019-08-12 at Mon 12-8 3 23pm](https://user-images.githubusercontent.com/31054815/62846666-49b3e500-bd15-11e9-831d-08e652d48008.png)
Fig 18 from [the paper](https://doi.org/10.5194/gmd-2019-106).  Ombai and Lombok Str transports at 1 deg (blue) are weaker than observed by INSTANT. Figure script is [here](https://github.com/COSIMA/ACCESS-OM2-1-025-010deg-report/blob/master/figures/strait_transports/strait_transports.ipynb).

**Comment by aekiss** [comment]
ping @kialstewart

**Comment by aekiss** [comment]
AFAIK the missing bottom points at Lombok and Ombai were an oversight due to switching from GFDL50 to the KDS50 vertical grid.

**Comment by sjmarsland** [comment]
The Rayleigh damping should certainly extend to the bottom in Ombok and Lombai Straits. I am a little confused by the top figure (small circles indicating cells). For the Arakawa B-grid the velocity point is on the north-east corner of the cell, and it is here where the damping is applied. Note Ombok and Lombai should be two tracer cells wide, with one vector point active in between.

**Comment by aekiss** [comment]
@sjmarsland the top 2 panels show velocity cells, not tracer cells (i.e. white cells are the U-grid land mask), so that's why those straits are one cell wide.

It looks like there was an off-by-one error in the `field_table` entry specifying the j index for damping in Torres Strait, so presumably this should be extended to cover the full width?

**Comment by sjmarsland** [comment]
Yes, should cover the full width of Torres Strait

**Comment by aekiss** [comment]
closing - this is fixed in the ak_dev branch
