### ISSUE TITLE
Problem with input_08022019 - uses old GFDL vertical grid

### ISSUE THREAD

**Issue by rmholmes** [COSIMA/access-om2#159]
After much dectectoring I have tracked the problems Maurice and I have been having with restarting the new `025deg_jra55_iaf` configs and executables from the GMD2019 5th cycle restarts.

I no longer get dropping minimum salinities, which eventually cause the model to crash late in the first year because of negative salinities near -231W,  72N (a bay in the siberian-arctic coast with what looks like lots of runoff) if I revert the `input_08022019/mom_025deg` back to the GMD2019 version `input_236a3011/mom_025deg`. Diff'ing these two folders:
```
[rmh561@raijin6 access-om2]$ diff /short/public/access-om2/input_08022019/mom_025deg/ /short/public/access-om2/input_236a3011/mom_025deg/
Binary files input_08022019/mom_025deg/ocean_temp_salt.res.nc and input_236a3011/mom_025deg/ocean_temp_salt.res.nc differ
Binary files input_08022019/mom_025deg/ocean_vgrid.nc and input_236a3011/mom_025deg/ocean_vgrid.nc differ
Binary files input_08022019/mom_025deg/topog.nc and input_236a3011/mom_025deg/topog.nc differ
```

an `ncdiff` of these files is at `/short/public/rmh561/access-om2/input_diffs/`). I suspect that some changes in topography are causing out-of-range salinity values to be pulled in somehow (in the restoring?), but there's nothing obvious I can see. @russfiedler @aekiss do you have any hints here? Do you know why these inputs changed, and has anyone else tested them?

**Comment by rmholmes** [comment]
Note: The same problem afflicts `input_08022019/mom_1deg` - it was causing problems with restarting the most recent `1deg_jra55_ryf` from Fabio's 1-degree restarts at `/g/data/hh5/tmp/cosima/access-om2/1deg_jra55_ryf9091_spinup1_B1/output141/`

**Comment by russfiedler** [comment]
Those grids and topographies are vastly different. One is based on Kial's 51 level grid (236a3011) 2.3m top layer extending to 5363m and the other is based on GFDL's(?) 51 levels 10.067m top layer extending to 5500m

**Comment by rmholmes** [comment]
Ahh ok, thanks. 

So why are the most recent [control configs](https://github.com/COSIMA/access-om2/tree/master/control) pointing to a version of the input files which are based on the old GFDL grid? @aekiss do you know?

**Comment by russfiedler** [comment]
The 1 degree grid changed too.

**Comment by aekiss** [comment]
Gah! It looks like I was responsible for the offending commit back in May https://github.com/COSIMA/025deg_jra55_iaf/commit/a15bc283e63e731d63baada702bacc5fda38d29b - I'm terribly sorry for all the hassle and time this has cost you. 

As I recall, @nichannah created `input_08022019` to update the 0.1 deg topography and I assumed that it had the latest versions of all input files, but hadn't checked. Apparently it had some really old files in it.

I made the same commit to all the 1 and 0.25 deg JRA configs. I'll fix them.

I think this points to a need for a more systematic process for checking the configs - maybe there should be a beta branch?

Again,  my apologies.

**Comment by rmholmes** [comment]
No worries @aekiss, happens to everyone. I should have been more on top of checking the inputs.

For testing, it'd be great to do some automatic cheap runs of the 1-degree configurations everytime the configs (inputs/executables) are updated? I feel that that would catch most errors (given the large equivalence across the different resolutions). 

However, it might not have caught this error because it seems to work fine starting from WOA initial conditions.

**Comment by russfiedler** [comment]
Maybe a script performing diffs or checksums of the forcing fields/grids etc logging what has changed from version to version?

**Comment by aekiss** [comment]
well I owe both of you at least a beer. 
Yes we were just discussing improving the process, checking input hashes via manifests.

**Comment by aekiss** [comment]
Inputs for `025deg_jra55_ryf` now differ from the other 0.25 and 1 deg JRA configs. They should probably be brought into alignment (but not before checking!)

**Comment by rmholmes** [comment]
Great, thanks Andrew. Feel free to close this issue when you're happy with `025deg_jra55_ryf`. We will continue testing and let you know if we run into problems

**Comment by mauricehuguenin** [comment]
Thanks Andrew for updating [025deg_jra55_iaf](https://github.com/COSIMA/025deg_jra55_iaf). I just did a 3-year run and it looks like everything is working as expected now.

**Comment by aekiss** [comment]
That's great to hear, thanks for letting me know.
Bear in mind that there are some other issues that are yet to be fixed in that configuration (in addition to the changes already in the ak-dev branch, which is yet to be merged into master).

**Comment by aekiss** [comment]
I've copied `ocean_vgrid.nc` and `topog.nc` from `input_236a3011` to the release candidate`/short/public/access-om2/input_rc` at 1 deg and 0.25 deg:
```
cp /short/public/access-om2/input_236a3011/mom_025deg/ocean_vgrid.nc /short/public/access-om2/input_rc/mom_025deg/ocean_vgrid.nc
cp /short/public/access-om2/input_236a3011/mom_025deg/topog.nc /short/public/access-om2/input_rc/mom_025deg/topog.nc
cp /short/public/access-om2/input_236a3011/mom_1deg/ocean_vgrid.nc /short/public/access-om2/input_rc/mom_1deg/ocean_vgrid.nc
cp /short/public/access-om2/input_236a3011/mom_1deg/topog.nc /short/public/access-om2/input_rc/mom_1deg/
```
@rmholmes, @russfiedler - this is all I need to fix, right?

**Comment by russfiedler** [comment]
I believe that looks right.

**Comment by rmholmes** [comment]
```
[rmh561@raijin5 access-om2]$ diff -r input_236a3011/ input_rc/
Binary files input_236a3011/cice_01deg/grid.nc and input_rc/cice_01deg/grid.nc differ
Binary files input_236a3011/cice_01deg/kmt.nc and input_rc/cice_01deg/kmt.nc differ
Only in input_rc/common_01deg_jra55: rmp_jra55_to_cice_1st_conserve.nc
Only in input_rc/common_01deg_jra55: rmp_jra55_to_cice_2nd_conserve.nc
Only in input_rc/common_01deg_jra55: rmp_jra55_to_cice_patch.nc
Only in input_rc/: common_025deg_core
Only in input_236a3011/mom_01deg: new_salt.nc
Binary files input_236a3011/mom_01deg/ocean_mask.nc and input_rc/mom_01deg/ocean_mask.nc differ
Binary files input_236a3011/mom_01deg/ocean_temp_salt.res.nc and input_rc/mom_01deg/ocean_temp_salt.res.nc differ
Binary files input_236a3011/mom_01deg/ocean_vgrid.nc and input_rc/mom_01deg/ocean_vgrid.nc differ
Binary files input_236a3011/mom_01deg/salt_sfc_restore.nc and input_rc/mom_01deg/salt_sfc_restore.nc differ
Binary files input_236a3011/mom_01deg/topog.nc and input_rc/mom_01deg/topog.nc differ
Only in input_rc/mom_025deg: salt_sfc_restore-bkp.nc
Binary files input_236a3011/mom_025deg/salt_sfc_restore.nc and input_rc/mom_025deg/salt_sfc_restore.nc differ
Binary files input_236a3011/mom_1deg/salt_sfc_restore.nc and input_rc/mom_1deg/salt_sfc_restore.nc differ
Binary files input_236a3011/mom_1deg/ssw_atten_depth.nc and input_rc/mom_1deg/ssw_atten_depth.nc differ
Binary files input_236a3011/mom_1deg/temp_sfc_restore.nc and input_rc/mom_1deg/temp_sfc_restore.nc differ
Only in input_236a3011/: mom_1deg-old_grid
Only in input_rc/: README.txt
Only in input_rc/yatm_01deg: rmp_jra55_river_to_cice_2nd_conserve.nc
Only in input_rc/yatm_01deg: RYF.u_10.1984_1985_scale.nc
Only in input_rc/yatm_01deg: RYF.v_10.1984_1985_scale.nc
Only in input_rc/yatm_025deg: ncar_precip.0001.nc
Only in input_rc/yatm_025deg: ncar_rad.0001.nc
Only in input_rc/yatm_025deg: q_10.0001.nc
Only in input_rc/yatm_025deg: rmp_daitren_runoff_MOM025_conserve2nd.nc
Only in input_rc/yatm_025deg: runoff.daitren.clim.10FEB2011.nc
Only in input_rc/yatm_025deg: slp.0001.nc
Only in input_rc/yatm_025deg: t_10.0001.nc
Only in input_rc/yatm_025deg: u_10.0001.nc
Only in input_rc/yatm_025deg: v_10.0001.nc
Only in input_236a3011/: yatm_1deg_bkp
```
For 025deg and 1deg, the only things that catch my eye are the `salt_sfc_restore.nc`, `ssw_atten_depth.nc`, `temp_sfc_restore.nc` and the yatm files (are the yatm inputs supposed to duplicate with the files in `mom_***`, e.g. `ncar_precip.0001.nc` with `ncar_precip.nc`?) - are these all expected? I'm happy to check the differences but you probably know already.

**Comment by russfiedler** [comment]
The 3 files you note have had their time axes fixed so the diff is expected.

**Comment by aekiss** [comment]
Thanks @rmholmes, @russfiedler.
Time axis changes explain `salt_sfc_restore.nc`, `ssw_atten_depth.nc`, `temp_sfc_restore.nc`: https://github.com/COSIMA/access-om2/issues/49
but `mom_025deg/salt_sfc_restore.nc` has also been made smoother: https://github.com/COSIMA/access-om2/issues/74#issuecomment-520275363
AFAIK the extra YATM files are for CORE: https://github.com/COSIMA/access-om2/issues/162

**Comment by rmholmes** [comment]
Great thanks, looks good.

**Comment by aekiss** [comment]
Closing - this problem has been fixed in `input_rc` in all JRA55-do configurations.

More details on inputs for `025deg_jra55_ryf`: https://github.com/COSIMA/access-om2/issues/162#issuecomment-630030165
