### ISSUE TITLE
git pull issue

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/access-om2#163]
I think this is the same issue as this one (https://github.com/COSIMA/access-om2/issues/152#issue-458927434), but I am unable to git pull the latest code at the moment:

[hh0162@raijin4 short]$ git clone --recursive https://github.com/COSIMA/access-om2.git access-om2-hakaseh
...
remote: Compressing objects: 100% (79/79), done.
remote: Total 1324 (delta 69), reused 97 (delta 47), pack-reused 1198
Receiving objects: 100% (1324/1324), 168.19 KiB | 263 KiB/s, done.
Resolving deltas: 100% (853/853), done.
fatal: reference is not a tree: 1c3e116392d8b9f2e41daad351c09172e316ced8
Unable to checkout '1c3e116392d8b9f2e41daad351c09172e316ced8' in submodule path 'control/01deg_jra55_iaf'

**Comment by aekiss** [comment]
Oops, apologies for that @hakaseh. I've just pushed a fix which works for me. Try again and let me know how you go.

**Comment by hakaseh** [comment]
Thanks @aekiss, git pull worked this time.
