### ISSUE TITLE
Improve 1deg_core_nyf remapping files

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#164]
`1deg_core_nyf/namcouple` uses `common_1deg_core/rmp_nt62_to_cice_CONSERV_FRACNNEI.nc` for all fields other than wind, but something smooth would be better for air pressure, temperature and humidity. 
Wind uses `common_1deg_core/rmp_nt62_to_cice_DISTWGT.nc` which uses distance weighted avg of nearest neighbors, but other 1 deg configs use higher-order patch (`common_1deg_jra55/rmp_jra55_cice_smooth.nc`). So something like that should be used for wind, air pressure, temperature and humidity in this config.

Also see https://github.com/COSIMA/access-om2/issues/71

**Comment by aekiss** [comment]
I've just created `/short/public/access-om2/input_rc/common_1deg_core/CORE2_MOM1_patch.nc` using [this version of make_remap_weights.sh](https://github.com/COSIMA/access-om2/blob/esmf-conserve/tools/make_remap_weights.sh). 

I don't know if that would be a suitable replacement for `/short/public/access-om2/input_rc/common_1deg_core/rmp_nt62_to_cice_DISTWGT.nc`. 
There are some differences, e.g. 
```
	src_grid_corners = 4 ;
	dst_grid_corners = 4 ;
```
whereas in `rmp_nt62_to_cice_DISTWGT.nc` they're both 1.

**Comment by aekiss** [comment]
Also, `rmp_nt62_to_cice_CONSERV_FRACNNEI.nc` is conservative but at unspecified order - but presumably 1st order as it was created in 2013.
Perhaps the newly-created `CORE2_MOM1_conserve.nc` could be a replacement, but again there are differences, e.g. `num_wgts`.

**Comment by aekiss** [comment]
caveat: running `make_remap_weights.py` produced a lot of messages like
```
[raijin1:24039] shmem: posix: file name search - max attempts exceeded.cannot continue with posix.
```
- not sure if that's cause for concern

**Comment by nichannah** [comment]
Hi @aekiss, it looks like 1deg_core_nyf weights are left over from the old OASIS/SCRIP (https://github.com/SCRIP-Project/SCRIP) way of creating the weights. We moved away from this because ESMF is a lot more scalable (and generally better). Therefore we can't expect to get the same weights from the new way of doing things. This change is going to change answers. 

I've self-assigned this and will address it along with https://github.com/COSIMA/access-om2/issues/71

**Comment by nichannah** [comment]
Just to confirm what @aekiss has said: the 1 deg core remapping files being used are from the old SCRIP-based remapping weights approach. There are two (minor) problems with this:

1. not consistent with the other experiment setups
2. no 'patch' interpolation is being used which is preferable for scalar fields.

**Comment by aekiss** [comment]
core configs are deprecated, so fixing this is a very low priority https://github.com/COSIMA/access-om2/issues/183

**Comment by aekiss** [comment]
core configs are no longer supported, so closing this issue
