### ISSUE TITLE
build with latest netcdf

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#166]
from https://opus.nci.org.au/display/Help/Gadi%3A+NCI%27s+New+Supercomputer
"Only the latest versions of third-party software packages will be built and installed on the new HPC system."

so I guess we should get NCI to install [netcdf 4.7.0](https://www.unidata.ucar.edu/blogs/news/entry/netcdf-4-7-0) and build with that?

Also see https://github.com/COSIMA/access-om2/issues/157, https://github.com/COSIMA/libaccessom2/issues/24

**Comment by russfiedler** [comment]
Also if/when we decide to use PIO in CICE we'll need 4.7.0.

**Comment by aekiss** [comment]
Update - [netcdf 4.7.1 has now been released](https://www.unidata.ucar.edu/blogs/news/entry/netcdf-4-7-1).

**Comment by aekiss** [comment]
@russfiedler: "PIO can use NetCDF (version 4.6.1+)": https://github.com/NCAR/ParallelIO

**Comment by aekiss** [comment]
link to related PIO issue in CICE: https://github.com/COSIMA/cice5/issues/34

**Comment by russfiedler** [comment]
@aekiss Actually, the problem is with the HDF5 library that NCI have linked V4.6.1 to. The bug is fixed in 1.10.4. It's likely we don't trigger the bug as it's related to processors failing to take part in the collective writes I think, but you never know...

 https://groups.google.com/forum/#!topic/parallelio/LE7qnAlhP38

**Comment by aekiss** [comment]
note to self: NetCDF 4.7.1. install request: https://track.nci.org.au/servicedesk/customer/portal/5/HELP-163544

**Comment by aekiss** [comment]
The NetCDF version would need to be updated in numerous places:
```
${ACCESS_OM_DIR}/src/mom/bin/environs.nci
${ACCESS_OM_DIR}/src/cice5/bld/config.nci.auscom.360x300 
${ACCESS_OM_DIR}/src/cice5/bld/config.nci.auscom.1440x1080 
${ACCESS_OM_DIR}/src/cice5/bld/config.nci.auscom.3600x2700 
${ACCESS_OM_DIR}/src/libaccessom2/build_on_raijin.sh 
${ACCESS_OM_DIR}/src/libaccessom2/build/oasis3-mct-prefix/src/oasis3-mct/util/make_dir/config.nci
```
Have I missed anything?

`libcheck.sh` is intended to give us an overview of all this.

**Comment by aekiss** [comment]
Netcdf 4.7.1 was compiled with Intel 19 so the model components all need to be compiled with this version to use Netcdf 4.7.1.

**Comment by aekiss** [comment]
https://github.com/COSIMA/access-om2/pull/178 builds with 
intel-compiler/2019.5.281
netcdf/4.7.1
openmpi/4.0.1

**Comment by aekiss** [comment]
[netCDF 4.7.3](https://www.unidata.ucar.edu/blogs/news/entry/netcdf-4-7-3) is the latest currently installed on gadi, and we're currently compiling with netcdf/4.7.1
[netCDF 4.7.4](https://www.unidata.ucar.edu/blogs/news/entry/netcdf-4-7-4) was released on 2 April. Should we request this for gadi? 
The latest NetCDF-Fortran release is [v4.5.2](https://github.com/Unidata/netcdf-fortran/releases) (newer than NetCDF-Fortran v4.5.1 that goes with netCDF 4.7.1).

**Comment by aekiss** [comment]
From @nichannah on [slack](https://arccss.slack.com/archives/CC78YM9EE/p1589955200023700)
> the latest version of netcdf (4.7.4) supports compression with parallel I/O writes

https://www.unidata.ucar.edu/software/netcdf/docs/RELEASE_NOTES.html#autotoc_md1
Compression will be great to have with PIO in CICE (https://github.com/COSIMA/cice5/issues/34).

**Comment by aekiss** [comment]
closing - we're now building access-om2 with `netcdf/4.7.4` and `netcdf/4.7.4p`.
