### ISSUE TITLE
Build model error: build_on_raijin.sh: file not found

### ISSUE THREAD

**Issue by Acosta-Goncalves** [COSIMA/access-om2#169]
I'm starting my work with the OM2 model following the "Getting started" guide. When building the models with the command `./install.sh`, I kept getting an error saying: 
`source: build_on_raijin.sh: file not found`

After some googling, I fixed the error by changing the `install.sh` file, line 34 from:
`source build_on_raijin.sh`
to
`source ./build_on_raijin.sh`

I'm not sure if this has been an issue just for me, but I'm just leaving it here in case somebody needs a fix for it.

**Comment by penguian** [comment]
I can confirm.

**Comment by aekiss** [comment]
Thanks @Acosta-Goncalves and @penguian, I've added this fix to the master.
