### ISSUE TITLE
Work with Environment Modules 4 on Gadi

### ISSUE THREAD

**Issue by penguian** [COSIMA/access-om2#175]
Today I tried running on Gadi. Building succeeded. Unfortunately, I was unable to run the 1deg_jra55_ryf  experiment. The error in [payu/envmod.py](https://github.com/payu-org/payu/blob/master/payu/envmod.py) line 40 is
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/Modules/v4.3.0/init/.modulespath’
```
Payu needs to be updated for this experiment to succeed. This might not require changes to access-om2 itself, but the issue is still worth recording here. See payu issue https://github.com/payu-org/payu/issues/209

**Comment by aidanheerdegen** [comment]
Fixed in https://github.com/payu-org/payu/pull/211

Updated `payu` is in `conda/analysis3-unstable`
