### ISSUE TITLE
Remove minimal and core configs from access-om2 repo

### ISSUE THREAD

**Issue by nichannah** [COSIMA/access-om2#183]
On a fresh pull the access-om2 control directory contains the following experiments:

```
01deg_jra55_iaf
01deg_jra55_ryf
025deg_core2_nyf
025deg_jra55_iaf
025deg_jra55_ryf
1deg_core_nyf
1deg_jra55_iaf
1deg_jra55_ryf
minimal_01deg_jra55_iaf
minimal_01deg_jra55_ryf
```

We should bring this down to the minimum that will be tested and maintained as code or standard configs change. AFAIK he minimal_ configs are not used much and could be dropped.

**Comment by aekiss** [comment]
I agree. 

This was discussed in https://arccss.slack.com/archives/C6PP0GU9Y/p1574995599016100
The consensus seemed to be that we should cease maintenance of these
```
025deg_core2_nyf
1deg_core_nyf
```
and maintain these only when needed for dev work
```
minimal_01deg_jra55_iaf
minimal_01deg_jra55_ryf
```
and that none of these four should be in the access-om2 control directory, i.e. leave them all on github, but don't include these four as submodules in access-om2.

**Comment by aekiss** [comment]
A quick bit of googling shows there are many recipes for "the one right way" to remove submodules. What's worse, most of them have a surprising number of steps, including making changes in .git, which seems dodgy. 

Does anyone have a recommended method?

**Comment by aekiss** [comment]
I've just pushed commit 9438eba81b6036fda9de60fce4a983ca37b1d690 obtained by doing this on the `issue-183` branch:
```
git submodule deinit -- control/1deg_core_nyf
git submodule deinit -- control/025deg_core2_nyf
git submodule deinit -- control/minimal_01deg_jra55_iaf
git submodule deinit -- control/minimal_01deg_jra55_ryf
git rm control/1deg_core_nyf
git rm control/025deg_core2_nyf
git rm control/minimal_01deg_jra55_iaf
git rm control/minimal_01deg_jra55_ryf
```
I think this is all that's needed to remove these submodules. The interwebs are [a bit confusing](https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule/7646931#7646931) on this point, as the best way to do it seems to depend on git version (I used git version 2.25.1).

**Comment by aekiss** [comment]
resolved in https://github.com/COSIMA/access-om2/pull/195
