### ISSUE TITLE
Tidy neutral physics in input.nml

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#197]
Following https://arccss.slack.com/archives/C9Q7Y1400/p1588727336089300

MOM's neutral physics settings in `&ocean_nphysics_util_nml` in `input.nml` are confusing because many ignored parameters are specified. 

The ACCESS-OM2 configurations are explained in section 3.2.5 of the [technical report](http://cosima.org.au/wp-content/uploads/2020/03/ACCESS-OM2-1-025-010deg-2020-03-12-02bf205.pdf), and the relevant code is [ocean_nphysics_util.F90](https://github.com/mom-ocean/MOM5/blob/cc35eebcebcb4c269b2f68dbe1fa93f091941f5e/src/mom5/ocean_param/neutral/ocean_nphysics_util.F90).

Here are the changes I think should be made to clarify `&ocean_nphysics_util_nml` in `input.nml`:

**for the 0.1 deg configurations:**
- remove everything in  `ocean_nphysics_util_nml` - ignored because `use_this_module = .false.` in `&ocean_nphysics_nml`

**for the 1 deg and 0.25 deg configurations:**
- remove `agm` - ignored because `agm_closure = .true.`
- remove `rossby_radius_min` and `rossby_radius_max` - ignored because `agm_closure_length_rossby = .false.`
- remove `agm_closure_eden_gamma` - ignored because `agm_closure_eden_greatbatch = .false.`
- remove `vel_micom` - ignored because `tracer_mix_micom = .false.`
- remove `agm_damping_time` - ignored because `agm_smooth_time = .false.`
- remove these because they take the default value `.false.`
  - `agm_closure_length_rossby`
  - `agm_closure_eden_greatbatch`
  - `tracer_mix_micom`
  - `agm_closure_length_fixed`
  - `drhodz_smooth_horz`
  - `drhodz_smooth_vert`
  - `agm_closure_length_bczone`
  - `agm_smooth_space`
  - `agm_smooth_time` 

Does this look OK @russfiedler, @rmholmes, @AndyHoggANU ?

**Comment by AndyHoggANU** [comment]
Looks OK to me. Thanks.

**Comment by StephenGriffies** [comment]
@aekiss I agree with removing those nml options that are not used in the configuration.  neutral physics has heaps of options and best to focus just on those that are used by the configuration.

**Comment by rmholmes** [comment]
Good idea, thanks Andrew.

I imagine there is many similar non-neccessary default options in lots of the other namelists where a similar thing could be done.

**Comment by aekiss** [comment]
Agreed, there is plenty more redundancy in the namelists. Checking them is a bit of a tedious slog though (e.g. some defaults are true rather than false, etc)...

**Comment by aekiss** [comment]
Closed - I've made these changes in the `ak-dev` branches in all JRA configs
