### ISSUE TITLE
wombat in master

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/access-om2#209]
I'm wondering if wombat in master is ready for test runs? 

To create the executables with wombat, I modified install.sh as follows:

#export mom_type=ACCESS-OM
export mom_type=ACCESS-OM-BGC

Then I did ./install.sh, then got the following error: 

/scratch/v45/hh0162/access-om2/src/mom/src/ice_sis/ice_model.F90(273): remark #15009: ice_model_mod_mp_sum_top_quantities_ has been targeted for automatic cpu dispatch
/scratch/v45/hh0162/access-om2/src/mom/src/ice_sis/ice_model.F90(1541): remark #15009: ice_model_mod_mp_ice_redistribute_ has been targeted for automatic cpu dispatch
/scratch/v45/hh0162/access-om2/src/mom/src/ice_sis/ice_model.F90(1747): remark #15009: ice_model_mod_mp_ext_ has been targeted for automatic cpu dispatch
mpifort -Duse_netCDF -Duse_netCDF3 -Duse_libMPI -DUSE_OCEAN_BGC -DENABLE_ODA -DSPMD -DLAND_BND_TRACERS  -fpp -Wp,-w -I/apps/netcdf/4.7.1/include -I/home/581/hh0162/scratch/access-om2/src/libaccessom2/oasis3-mct/Linux/build/lib/psmile.MPI1 -I/home/581/hh0162/scratch/access-om2/src/libaccessom2/oasis3-mct/Linux/build/lib/mct -I/home/581/hh0162/scratch/access-om2/src/libaccessom2/build/include -fno-alias -safe-cray-ptr -fpe0 -ftz -assume byterecl -i4 -r8 -traceback -nowarn -check noarg_temp_created -assume nobuffered_io -convert big_endian -grecord-gcc-switches -align all -g3 -O2 -axCORE-AVX2 -debug all -check none -qopt-report=5 -qopt-report-annotate -I/home/581/hh0162/scratch/access-om2/src/mom/exec/nci/lib_FMS -c	/home/581/hh0162/scratch/access-om2/src/mom/src/ice_sis/mask.F90
ifort: remark #10397: optimization reports are generated in *.optrpt files in the output location
/scratch/v45/hh0162/access-om2/src/mom/src/ice_sis/mask.F90(24): remark #15009: mask_mod_mp_make_v_grid_ has been targeted for automatic cpu dispatch
/scratch/v45/hh0162/access-om2/src/mom/src/ice_sis/mask.F90(54): remark #15009: mask_mod_mp_make_mask_ has been targeted for automatic cpu dispatch
ar rv lib_ice.a ice_spec.o ice_albedo.o ice_grid.o ocean_albedo.o ice_dyn.o ice_bergs.o rot.o ice_type.o ocean_rough.o ice_model.o ice_thm.o mask.o
ar: creating lib_ice.a
a - ice_spec.o
a - ice_albedo.o
a - ice_grid.o
a - ocean_albedo.o
a - ice_dyn.o
a - ice_bergs.o
a - rot.o
a - ice_type.o
a - ocean_rough.o
a - ice_model.o
a - ice_thm.o
a - mask.o
Error: unsupported model type, please see model types in ./MOM_compile.sh --help

**Comment by russfiedler** [comment]
It looks like you've still got the old versions of the submodules for MOM, CICE and libaccessom2.

**Comment by aekiss** [comment]
No need to compile this yourself - I've already done it.

Start with a config from the ak-dev branch - this should work with v1.4.0 with no modification, but this will be a non-BGC config.

To use the BGC MOM executable, change
      `exe: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM_08cf2b5_libaccessom2_a9d4b67.x`
to
      `exe: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM-BGC_08cf2b5_libaccessom2_a9d4b67.x`
in config.yaml.

I haven't tried running this executable. I understand from Russ that additional inputs will be required. These could be put in a new directory in /g/data/ik11/inputs/access-om2 and added as additional input items in config.yaml (laid out in a list as was done for the atmosphere inputs). There will also need to be changes to namcouple and probably a few other things.

**Comment by russfiedler** [comment]
Hakase wants to add extra BGC stuff to CICE so he does need to compile it.

**Comment by aekiss** [comment]
Ah ok, the submodules make it tricky so simplest thing is a brand-new recursive clone:
```
git clone --recursive https://github.com/COSIMA/access-om2.git
```
then checkout the `ak-dev` control branches, set up new `bgc` config branches, and recompile:
```
cd access-om2
cd control
for d in *; do cd $d; git checkout ak-dev; git checkout -b bgc; cd ..; done
cd ..
./install.sh
```
these (non-BGC) configs should all work as-is.

**Comment by aekiss** [comment]
you'll also need to modify `install.sh` as you did before:
```
#export mom_type=ACCESS-OM
export mom_type=ACCESS-OM-BGC
```

**Comment by aekiss** [comment]
note that the install script will not update config.yaml to use the BGC versions - you'll need to do that by hand.

**Comment by hakaseh** [comment]
Thanks guys.

Would it be ok if I do ./install.sh first, and then checkout the ak-dev control branches? ak-dev is only for the config, so would not affect the model code, right? I started ./install.sh before seeing your message about ak-dev.

**Comment by aekiss** [comment]
yes that's fine, it was just so at the end of the script it would update the executable paths in config.yaml. You can let the install finish, then check out ak-dev in the config(s) then run install.sh again (or just run hashexe.sh). install.sh is much quicker the second time.

**Comment by hakaseh** [comment]
Switching to v1.4.0 seems to work successfully.

I noticed that config.yaml did not update the ocean executable after ./install.sh, although it did for yatm and cice. I checked the output of install.sh, and noticed the following warning message:

WARNING: mom_type is not ACCESS-OM, so MOM exe not updated in any config.yaml file

Is this expected? If so, do I need to manually replace the default ocean executable with my own executable in config.yaml?

**Comment by aekiss** [comment]
Yes, this is a known issue (https://github.com/COSIMA/access-om2/issues/208), which is why that warning is given.

So you'll need to make that exe change in config.yaml manually.

**Comment by hakaseh** [comment]
ok. I made changes to config.yaml manually.

I submitted a job, but it stopped during the initialization (see the last few lines of access-om2.out below). I noticed a difference between the default ocean/input.nml and the one used for wombat test run by Russ (see my diff output below). @russfiedler is this the namelist I should be using?

diff output

```
(base) [hh0162@gadi-login-04 ocean]$ diff input.nml ~/raf599_bgc/output000/ocean/input.nml 
34,35c34,35
<                 'q_flux', 't_flux', 'lw_flux', 'runof', 'p', 'aice', 'wfimelt',
<                 'wfiform', 'licefw', 'liceht'
---
>                 'q_flux', 't_flux', 'lw_flux', 'runof', 'p', 'aice', 'wfimelt', 
>                 'wfiform', 'wnd_io'
37c37
<     num_fields_in = 17
---
>     num_fields_in = 16
334c334,335
<     max_delta_salinity_restore = -0.5
---
>     max_delta_salinity_restore = 0.5
>     salinity_restore_limit_upper=40
418a420
>     pottemp_equal_contemp = .true.
```




access-om2.out

```
                                                   ======== COMPLETED MOM INITIALIZATION ========



 &MOM_OASIS3_INTERFACE_NML
 NUM_FIELDS_IN   =          16,
 NUM_FIELDS_OUT  =           7,
 FIELDS_IN       = u_flux  v_flux  lprec   fprec   salt_flxmh_flux sw_flux q_flux  t_flux  lw_flux runof   p       aice    wfimelt wfiform wnd_io  ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@,
 FIELDS_OUT      = t_surf  s_surf  u_surf  v_surf  dssldx  dssldy  frazil  ^@^@^@^@^@^@^@^@,
 SEND_BEFORE_OCEAN_UPDATE        = F,
 SEND_AFTER_OCEAN_UPDATE = T
 /
 CICE_COMMIT_HASH=26e61591c985ee76a10366dcba51fb99e6d84f61
 cicexx: LIBACCESSOM2_COMMIT_HASH=a9d4b678166642f0a7639a8a878afcfec1f35c4f
```

**Comment by russfiedler** [comment]
@hakaseh 

My test case was made before `licefw` and `liceht` were being passed between the modules and before JRA55-do-1-4-0 so there will be some problems.

You'll need to add `wnd_io` to your `input_nml` and increase the number of fields to 18

##########
# Field 29 : 10 m winds
########## 
wnd10_io wnd_io 36 5400 1 i2o.nc IGNORED
cict cict LAG=0 SEQ=+1
#
LOCTRANS
INSTANT

to the namcouple file as well as increasing the number of fields to `36`.

`ice/input_ice.nml` needs 'wnd_io' added to fields_ocean

You'll also need the input files in 

/g/data/v19/raf599/wombat_test/wombat_1deg_jra55_ryf/bgc        (mom)
/g/data/v19/raf599/wombat_test/wombat_1deg_jra55_ryf/bgc_ice (cice)

You will also need to create a new `i2o.nc` file The one I have in /g/data/v19/raf599/wombat_test/wombat_1deg_jra55_ryf/bgc_ice doesn't have ` licefw_io` nor `licefh_io`

**Comment by hakaseh** [comment]
@russfiedler  I followed your instructions, and this time the run stopped with the following message in access-om2.out:

 YATM_COMMIT_HASH=a9d4b678166642f0a7639a8a878afcfec1f35c4f
 matmxx: LIBACCESSOM2_COMMIT_HASH=a9d4b678166642f0a7639a8a878afcfec1f35c4f

i have no idea what this means 😅

**Comment by russfiedler** [comment]
Hi, your MOM restarts are being put into you CICE restart directory but the MOM directory looks ok however there needs to be wnd10_io field in  `i2o.nc`

Try the version at `/g/data/v19/raf599/wombat_test/wombat_1deg_jra55_ryf/bgc_ice/i2o_hakase.nc`

**Comment by hakaseh** [comment]
@russfiedler I created i2o.nc that merges wnd10_io with the default config for v1.4.0 using ncks, which is identical to yours. I tested using both but gave the same error message I previously noted above.

On the side note, what happens if there are two files of the same name in two different input directories. For example, i2o.nc is present in the default input directory for CICE (config.yaml):

```
input: 
       - /g/data/ik11/inputs/access-om2/input_20200422/cice_1deg
       - /home/581/hh0162/scratch/input-access-om2/mom_1deg
```

where I put my i2o.nc in the second directory. Which file would the model read? To avoid potential error, I copied all files (except i2o.nc) in the default directory to my directory, commented the default directory path, and ran the model, but got the same error.

**Comment by aidanheerdegen** [comment]
The first input directory takes precedence. But you can always check by doing
```
payu setup
```
and then `ls -l` in the `work` subdirectory to see where the symbolic link is pointing to. Or look in for `i2o.nc` in the `manifest/input.yaml` file, the `fullpath` shows where it is picking up the file.

`payu` will not run if there is already a `work` directory, so make sure you do
```
payu sweep
```
before your run, or 
```
payu run -f
```
which will automatically `sweep` before running if there is a `work` directory present.

**Comment by hakaseh** [comment]
thanks @aidanheerdegen i did not know the way to check, which is useful. i see that my files were linked correctly. i also do payu sweep to clean up the work directory.

**Comment by aidanheerdegen** [comment]
There is pretty good documentation for payu

https://payu.readthedocs.io/en/latest/

I'm always happy to hear how it can be improved if there is something that isn't clear.

**Comment by hakaseh** [comment]
@russfiedler could you do a test run to check if it runs successfully?

I tried using the executable provided in /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM-BGC_08cf2b5_libaccessom2_a9d4b67.x, but no success.

**Comment by hakaseh** [comment]
Happy to share the news of my first successful run with ACCESS-OM2-wombat!

I will now do a few more runs to check if I can run the model with initial and boundary bgc conditions for OMIP.

A question for @russfiedler and @aekiss : Is it possible to do physics-only runs with the executable that has wombat? if so, do you think it would be better to have only one executable (hence no need to modify the variable in install.sh)?

**Comment by russfiedler** [comment]
Good question. Yes, you can do physics only runs. I thinks there's a namelist parameter probably along the style of `use_this_module=.false.` . I don't think it will be a problem but somebody may want to run the combo of MOM/SIS and CSIRO-BGC I've left open the possibility of doing that. It's a bit awkward if you force WOMBAT into the ACCESS build. There is a bit of an overhead I think but not much. The philosophy of MOM seems to be to just keep the components you need and I've tried to stick to that.

**Comment by hakaseh** [comment]
thanks for your insights @russfiedler. maybe we can revisit this when wombat becomes more common.

Another question... i tried initialising with my own BGC ininitial fields (I created this using Python) and got this error:

_FATAL from PE     1: fms_io(restore_state_one_field): Checksum of input field CACO3               0 does not match value E1128609DB6D35F4stored in CSIRO_BGC.RES.NC._

It seem that it can be resolved by following this: https://github.com/payu-org/payu/issues/190

However, I can't find the MOM_input file anywhere in the config. Is there such a file in access-om2?

**Comment by aidanheerdegen** [comment]
HI Hakase,

The issue you've linked to is for `MOM6`, hence the `MOM_input` file.

Put this:
```
&fms_io_nml
    checksum_required=.false.
/
```
in your `ocean/input.nml` (add to `fms_io_nml` namelist if it exists already)

**Comment by hakaseh** [comment]
thanks @aidanheerdegen, that resolved the issue.
