### ISSUE TITLE
Non-advective points in 0.25deg topography

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#210]
We went to a lot of effort to eliminate problematic non-advective points in the 0.1deg `topog.nc` (https://github.com/COSIMA/access-om2/issues/99) but we still need to do the same for the other resolutions.

From https://arccss.slack.com/archives/C6PP0GU9Y/p1592289744341700?thread_ts=1592285883.339600&cid=C6PP0GU9Y
@russfiedler finds 21 non-advective columns in the grid at `/g/data/ik11/inputs/access-om2/input_20200530/mom_025deg/topog.nc`:
```
[raf599@gadi-login-02 topog]$ ./check_nonadvective_mosaic topog.nc
 depth dimensions        1440        1080
 Zeta dimensions         101          50
         816         651  0.0000000E+00   ! nonadvective
         819        1080   Surface North south nonadvective
         889          49    nonadvective, Deep          25          24
        1018         192    nonadvective, Deep          49          48
        1328         455    nonadvective, Deep          46          45
        1328         456    nonadvective, Deep          46          45
        1329         467    nonadvective, Deep          46          45
         196         494    nonadvective, Deep          26          25
         197         494    nonadvective, Deep          26          25
         176         554    nonadvective, Deep           9           0
         816         651    nonadvective, Deep           9           0
         246         742    nonadvective, Deep          11           0
         932         801    nonadvective, Deep          30          29
        1003         854    nonadvective, Deep          22          21
        1094         864    nonadvective, Deep          38          37
        1090         886    nonadvective, Deep          35          34
        1099         906    nonadvective, Deep          35          34
         169        1080    East west nonadvective, Deep          11          12
          11
         387        1080    East west nonadvective, Deep          40          41
          40
         862        1080    East west nonadvective, Deep          21          22
          21
        1153        1080    East west nonadvective, Deep          43          44
          43
```
Results and check program at `/scratch/v45/raf599/bathymetry`

It could also be worthwhile looking for choked estuaries with this tool https://github.com/aekiss/notebooks/blob/master/non-advective.ipynb

Other issues with this topography: https://github.com/mom-ocean/MOM5/issues/172, https://github.com/COSIMA/access-om2/issues/141, https://github.com/COSIMA/access-om2/issues/158

**Comment by aekiss** [comment]
I've just checked the 0.25 topography 
`/g/data/ik11/inputs/access-om2/input_20200530/mom_025deg/topog.nc`
with [non-advective.ipynb](https://github.com/aekiss/notebooks/blob/60f7e2a160e14d7d4d1f6c8a7b8ecf8b116a1eb0/non-advective.ipynb), which also checks the tripole and zonal joins.

There are 4 cells with no advective edges: 
`[(176, 554), (816, 651), (246, 742), (819, 1080)]`, 
ie the 3 that Russ found, plus an extra one on the tripole fold.

Here's what I think we should do with the non-advective cells if we remake this topog file: 

(176, 554), Philippines: change to land
![non_advective_cell_g_data_ik11_inputs_access-om2_input_20200530_mom_025deg_topog_nc_176_554](https://user-images.githubusercontent.com/31054815/84860543-90e7d080-b0b2-11ea-974c-dfd9e7dc7a24.png)

(816, 651), East coast USA: change to land
![non_advective_cell_g_data_ik11_inputs_access-om2_input_20200530_mom_025deg_topog_nc_816_651](https://user-images.githubusercontent.com/31054815/84860540-904f3a00-b0b2-11ea-87e9-1d3354b31c5a.png)

 (246, 742), Sakhalin: open channel (make (247, 742) the same depth as (246, 742))
![non_advective_cell_g_data_ik11_inputs_access-om2_input_20200530_mom_025deg_topog_nc_246_742](https://user-images.githubusercontent.com/31054815/84860537-8fb6a380-b0b2-11ea-89a0-b6d1325ffc35.png)

(819, 1080), Canadian Arctic: change to land
![non_advective_cell_g_data_ik11_inputs_access-om2_input_20200530_mom_025deg_topog_nc_819_1080](https://user-images.githubusercontent.com/31054815/84860532-8cbbb300-b0b2-11ea-9207-a9f8a66bc67c.png)

There's another 4 cells with at least one non-advective edge (see  [non-advective.ipynb](https://github.com/aekiss/notebooks/blob/60f7e2a160e14d7d4d1f6c8a7b8ecf8b116a1eb0/non-advective.ipynb)), but these don't choke the only outlet of an enclosed basin so aren't a concern:
` [(176, 554), (893, 739), (246, 741), (808, 1066)]`

**Comment by aekiss** [comment]
The 1deg topography 
`/g/data/ik11/inputs/access-om2/input_20200530/mom_1deg/topog.nc`
has 6 cells with non-advective edges 
`[(99, 92), (201, 227), (115, 235), (70, 269), (308, 291), (307, 293)]`
but no choked basin outlets and no cells with no advective edges, so that 1deg topography seems ok (at least from this point of view).

**Comment by russfiedler** [comment]
Actually, my program did find the point on the tripole. The output is a bit cryptic.

`819        1080   Surface North south nonadvective`

Completely agree with your suggested changes to the 0.25 land mask.

Also the non advective edge at (808,1066) is in your last plot above. As you note, no problem there

**Comment by ofa001** [comment]
Yes keep us in the loop of any grid land mask changes @russfiedler @aekiss we may want to revive out 0.25 degree coupled version in the next few months and any improvements could help though ongoing  land changes will impact CABLE group so that might be only a one time update, the last 0.25 degree coupled set up was with JULES scheme so they have to do the work anyway.

**Comment by aekiss** [comment]
Ah yes, I'd missed that tripole point in your list.

The only non-advective edge I'm a little worried by is (893, 739), which is in the channel to the west of Newfoundland (the Strait of Belle Isle):
![non_advective_edge_g_data_ik11_inputs_access-om2_input_20200530_mom_025deg_topog_nc_893_739](https://user-images.githubusercontent.com/31054815/84866755-80892300-b0bd-11ea-8079-d07b8caade53.png)

Here's a closeup, with a different depth scale: 
![non_advective_edge_g_data_ik11_inputs_access-om2_input_20200530_mom_025deg_topog_nc_893_739](https://user-images.githubusercontent.com/31054815/84867414-774c8600-b0be-11ea-8ebb-23d2b7a51233.png)

Newfoundland is a big island and in Gebco the channel is mostly deeper than the 40.36m (9 levels) minimum depth in topog.nc, so perhaps this channel should be opened up to allow some advective transport?
![gebco_894_740](https://user-images.githubusercontent.com/31054815/84869487-736e3300-b0c1-11ea-86fb-491cb72ba05e.png)

On the other hand, if we open up (893, 739) and the Sakhalin channel (247, 742) we might end up having to put in Rayleigh damping to avoid instability (as we did with the Kara Strait in the 0.1 model).

**Comment by aekiss** [comment]
Closing - this has been fixed in `/g/data/ik11/inputs/access-om2/input_20201022/` - see https://github.com/COSIMA/access-om2/issues/158#issuecomment-698758041
