### ISSUE TITLE
Incorrect information in namcouple files (all? configs)

### ISSUE THREAD

**Issue by russfiedler** [COSIMA/access-om2#211]
I don't think there's any  field being communicated from ice -> atm but the info in the `namcouple` files says there is and the totals don't match so it's a bit confusing.
e.g.

https://github.com/COSIMA/1deg_jra55_ryf/blob/master/namcouple#L14-L21

Just need to delete one line (19).

**Comment by aekiss** [comment]
thanks @russfiedler, I'll fix it
