### ISSUE TITLE
Shortwave partitioning is hardwired.

### ISSUE THREAD

**Issue by russfiedler** [COSIMA/access-om2#214]
For data assimilation purposes Pavel Sakov would like to change the way  shortwave is partitioned. This is easy in stand alone MOM-SIS.

At the moment the partitioning of the shortwave components is hardwired into the coupling. Only the full field is passed from CICE to MOM and the is apportioned. This is nasty.

https://github.com/mom-ocean/MOM5/blob/08cf2b5e7b068730f944b700010c61f36dbd2213/src/accessom_coupler/mom_oasis3_interface.F90#L645-L646

MOM can accept the individual components but this isn't implemented in CICE at the moment. 

`frac_vis_dir` etc should be able to be changed. The thing is where would the best place to read them in from? I guess just the `mom_oasis3_interface_nml` in order to keep it local but it's a bit odd to have it there.

**Comment by aekiss** [comment]
@russfiedler was this resolved with https://github.com/mom-ocean/MOM5/pull/327?

**Comment by russfiedler** [comment]
Yes, closing.
