### ISSUE TITLE
Suspicious decadal signal seen bottom pressure for ACCESS-OM2 @ 1 degree

### ISSUE THREAD

**Issue by navidcy** [COSIMA/access-om2#215]
I noticed a "weird" signal in bottom pressure for 1-degree model output. Seems like there is a decadal signal. I'm wondering whether this is physical (I doubt)... @AndyHoggANU mentioned that `1deg_jra55_ryf9091_gadi` has restarts every 10 year... Is this simply a coincidence or is it related with the restarts?

I tried to find the same signal in the `1deg_jra55_iaf_v2.0.0rc3` experiment which from what I understand has restarts every 5 years. It doesn't seem to be there... and perhaps one can see a 5-year equivalent? Not sure.

Any ideas on how to get to the bottom of this?

One might say that what matters are pressure differences across cells. However this signal also persists there; see figure below.

@aekiss, @rmholmes, @aidanheerdegen, @AndyHoggANU 

```python
session = cc.database.create_session()

x0, y0 = -45, -45
how_many_months = 620

fig, axs = plt.subplots(2, 1, figsize=(14, 8))

pbot_ryf_1 = cc.querying.getvar('1deg_jra55_ryf9091_gadi', 'pbot_t', session, frequency='1 monthly').sel({'xt_ocean': x0, 'yt_ocean': y0}, method='nearest').isel(time=slice(0, how_many_months))

axs[0].plot(pbot_ryf_1.time, pbot_ryf_1.values, marker=".")
axs[0].plot(pbot_ryf_1.time[::120], pbot_ryf_1.values[::120], marker="o", linestyle="none", color="r")
axs[0].set_xlabel("time")
axs[0].set_title("1deg_jra55_ryf9091_gadi: pbot_t at lon: "+str(x0)+", lat: "+str(y0), fontsize=14)

pbot_iaf_1 = cc.querying.getvar('1deg_jra55_iaf_v2.0.0rc3', 'pbot_t', session, frequency='1 monthly').sel({'xt_ocean': x0, 'yt_ocean': y0}, method='nearest').isel(time=slice(0, how_many_months))

axs[1].plot(pbot_iaf_1.time, pbot_iaf_1.values, marker=".")
axs[1].plot(pbot_iaf_1.time[::120], pbot_iaf_1.values[::120], marker="o", linestyle="none", color="r")
axs[1].set_xlabel("time")
axs[1].set_title("1deg_jra55_iaf_v2.0.0rc3: pbot_t at lon: "+str(x0)+", lat: "+str(y0), fontsize=14)

# compute pressure difference
pbot_ryf_1 = cc.querying.getvar('1deg_jra55_ryf9091_gadi', 'pbot_t', session, frequency='1 monthly')
dx_pbot_ryf_1 = (pbot_ryf_1.sel({'xt_ocean': x0, 'yt_ocean': y0}, method='nearest') - pbot_ryf_1.sel({'xt_ocean': x0, 'yt_ocean': y0-1}, method='nearest')).isel(time=slice(0, how_many_months))

plt.figure(figsize=(14, 4))
plt.plot(dx_pbot_ryf_1.time, dx_pbot_ryf_1.values, marker=".")
plt.plot(dx_pbot_ryf_1.time[::120], dx_pbot_ryf_1.values[::120], marker="o", linestyle="none", color="r")
plt.xlabel("time")
plt.title("1deg_jra55_ryf9091_gadi: difference of pbot_t between lon: "+str(x0)+", lat: "+str(y0)+" and lon: "+str(x0)+", lat: "+str(y0-1), fontsize=14)
```

<img width="852" alt="Unknown-1" src="https://user-images.githubusercontent.com/7112768/89859448-6282ff00-dbe4-11ea-806c-371b32e3e622.png">

<img width="862" alt="Unknown-2" src="https://user-images.githubusercontent.com/7112768/89859457-64e55900-dbe4-11ea-8b47-6ef2bf3185f8.png">

**Comment by rmholmes** [comment]
Curious. It's clearly associated with the first output of each 10-year section. E.g. see the below (generated from ncview `/g/data/ik11/outputs/access-om2/1deg_jra55_ryf9091_gadi/output0{28..29}/ocean/ocean_month.nc`):
<img width="692" alt="pbot_t_signal" src="https://user-images.githubusercontent.com/19428871/89860459-d7efcf00-dbe6-11ea-9c52-d2e2e2fc288c.png">

I am not sure. I couldn't find anything obvious like this in other variables. Perhaps @russfiedler might have some ideas as well?

**Comment by russfiedler** [comment]
I'm not convinced that Ext%pbot_t(:,:,tau) is set properly after restarting. It's just a diagnostic so doesn't affect anything (I think). We see `taup1` updated here 

https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_core/ocean_barotropic.F90#L2443-L2455

but the diagnostic is passed for `tau` a bit later

https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_core/ocean_barotropic.F90#L2599-L2601

So where is the `tau` step? `pbot_u` is in the barotropic restart but not `pbot_t`. I think `pbot_t(:,:,tau)` possibly should be there.

**Comment by rmholmes** [comment]
Oh I see.

Also note the note in the start of that subroutine 

https://github.com/mom-ocean/MOM5/blob/10d3bc02e6f3ccb78618bcef4a57b9b9fa848c79/src/mom5/ocean_core/ocean_barotropic.F90#L2402-L2405

Instead of adding it to the restart, would it be possible to just add a diagnostic at time `tau` there somewhere (since it sounds like rho is only known at time tau anyway)?

**Comment by russfiedler** [comment]
Yeah, I saw that but I think `pbot_t(taup1)` is restarted here and the time counter should have advanced by the time of the diagnostic.

https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_core/ocean_barotropic.F90#L5353

**Comment by navidcy** [comment]
@AndyHoggANU is this issue resolved/non-important? Should we close it or is there anything we should do about it?

**Comment by navidcy** [comment]
@AndyHoggANU I'll take you closing the issue as the answer to my question above.
But my question remains, is `pbot` variable wrong? Shall we not be using it?

**Comment by AndyHoggANU** [comment]
I think I would take it with a grain of salt, but not sure anyone is going to modify it...
