### ISSUE TITLE
input4MIPS paths changed

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/access-om2#218]
My simulation stopped during the third cycle of omip-2, which gives the following error:

**vi 1deg_jra55_iaf.e11009859**
payu: error: Input directory /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/rsds/gr/v20190429/rsds not found; aborting.

I don't know why this suddenly shows up. Anyway, I can't re-run the simulation because I can't do "payu sweep":

**payu sweep**
laboratory path:  /scratch/v45/hh0162/access-om2
binary path:  /scratch/v45/hh0162/access-om2/bin
input path:  /scratch/v45/hh0162/access-om2/input
work path:  /scratch/v45/hh0162/access-om2/work
archive path:  /scratch/v45/hh0162/access-om2/archive
payu: error: Input directory /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/rsds/gr/v20190429/rsds not found; aborting.

Any thoughts?

**Comment by aidanheerdegen** [comment]
Where is your control directory (where you run `payu`)?

What is the error you get when you try `payu sweep`?

**Comment by hakaseh** [comment]
Hi Aidan,

my control directory is: 

/scratch/v45/hh0162/access-om2/control/1deg_jra55_iaf_omip2

when I do payu sweep, i get:

laboratory path: /scratch/v45/hh0162/access-om2
binary path: /scratch/v45/hh0162/access-om2/bin
input path: /scratch/v45/hh0162/access-om2/input
work path: /scratch/v45/hh0162/access-om2/work
archive path: /scratch/v45/hh0162/access-om2/archive
payu: error: Input directory /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/rsds/gr/v20190429/rsds not found; aborting.

**Comment by aidanheerdegen** [comment]
The `input4MIPS` directories had spurious copies of the data that has, apparently, now been removed.

You will need to change the paths in `config.yaml` to remove the subdirectory, so it looks like so:
```
      input:
            - /g/data/ik11/inputs/access-om2/input_20200530/yatm_1deg
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/rsds/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/rlds/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/prra/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/prsn/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hrPt/psl/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/land/day/friver/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hrPt/tas/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hrPt/huss/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hrPt/uas/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hrPt/vas/gr/v20190429
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/landIce/day/licalvf/gr/v20190429
```

If you run `payu sweep && payu setup` then it should recreate the manifests and check those paths are ok. If they are then `sweep` again, or use `payu run -f` otherwise `payu` will complain there is already a `work` directory.

**Comment by hakaseh** [comment]
Ok. Do you think my previous simulations were affected by the spurious copies?

The same error message appears when I do "payu sweep && payu setup”:

laboratory path:  /scratch/v45/hh0162/access-om2
binary path:  /scratch/v45/hh0162/access-om2/bin
input path:  /scratch/v45/hh0162/access-om2/input
work path:  /scratch/v45/hh0162/access-om2/work
archive path:  /scratch/v45/hh0162/access-om2/archive
payu: error: Input directory /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/atmos/3hr/rsds/gr/v20190429/rsds not found; aborting.

**Comment by aidanheerdegen** [comment]
When you say the same error, after you make the changes I have suggested? Or is this referring to a different experiment? If so, where is the control directory?

**Comment by hakaseh** [comment]
oops, i skipped the first step to modify the paths in config.yaml.

your suggested changes work! thanks.

**Comment by aidanheerdegen** [comment]
I will reopen this as these changes need to be propagated to the IAF model configurations.

**Comment by aekiss** [comment]
I've also fixed the `ak-dev` branches of the IAF configs

**Comment by aekiss** [comment]
closing - this is fixed in the master branch of the 3 IAF configs.
