### ISSUE TITLE
Compiling with no optimisation

### ISSUE THREAD

**Issue by sakov** [COSIMA/access-om2#219]
I am putting up DA systems based on AOM2 configurations, and need to routinely investigate crashes caused by initialisation problems. I need to be able to investigate the core dumps generated, but could not find a way to compile all three executables (atmosphere, ice, ocean) with no optimisation. Any hints? Thanks!

**Comment by russfiedler** [comment]
Hi Pavel.

For MOM you need to add --debug to MOM_compile. For cice it's make DEBUG=1 and for yatm iI figured out that you need to you need to add -DCMAKE_BUILD_TYPE=Debug to cmake but that doesn't appear to propagate to the other modules. That may be sufficient.

I've made a script `install_debug.sh` in `/scratch/v14/raf599/acc/access-om2`. You'll also need two files in `/scratch/v14/raf599/acc/access-om2/src/libaccessom2`   `build_on_gadi.sh` and `build_debug.sh`.

You should get the options `-fpe0 -fp-model precise -fp-model source -align all -traceback -g3 -O0 -check all`

**Comment by sakov** [comment]
Thanks Russ, I will give it a go. Just to note that for cice one can avoid optimisation by adding "setenv DEBUG 1" to src/cice5/bld/build.sh.
