### ISSUE TITLE
ERROR: Directory '/g/data3/hh5/public/modules' not found

### ISSUE THREAD

**Issue by ctensubam** [COSIMA/access-om2#227]
Following the quick start tutorial [https://github.com/COSIMA/access-om2/wiki/Getting-started#quick-start](url) I have installed the model successfully but when I run the code ' module use /g/data/hh5/public/modules', it throws an error 'ERROR: Directory '/g/data3/hh5/public/modules' not found'. Where can I find the modules used in this model. Please help.

**Comment by scrallen** [comment]
Are you a member of project hh5?  This project host the conda environment managed by CLEX, and they will accept all membership requests without questions.

log in to mynci.org.au, and the projects you're a member of will be listed on the overview tab. 

If hh5 isn't listed:
- go to the 'projects and groups' tab 
- then 'find project or group' tab on the right
- search for hh5
- apply for membership

**Comment by ctensubam** [comment]
Thanks for the help.
