### ISSUE TITLE
Cannot check out cice submodule

### ISSUE THREAD

**Issue by MarkCheeseman** [COSIMA/access-om2#229]
Doing a recursive clone of the access-om2 (as directed in the installation instructions) fails while checking out the cice src as so:

git clone --recursive https://github.com/COSIMA/access-om2.git
Cloning into 'access-om2'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 2283 (delta 33), reused 58 (delta 23), pack-reused 2201
Receiving objects: 100% (2283/2283), 912.86 KiB | 399.00 KiB/s, done.
Resolving deltas: 100% (1394/1394), done.
Submodule 'control/01deg_jra55_iaf' (https://github.com/COSIMA/01deg_jra55_iaf.git) registered for path 'control/01deg_jra55_iaf'
Submodule 'control/01deg_jra55_ryf' (https://github.com/COSIMA/01deg_jra55_ryf.git) registered for path 'control/01deg_jra55_ryf'
Submodule 'control/025deg_jra55_iaf' (https://github.com/COSIMA/025deg_jra55_iaf.git) registered for path 'control/025deg_jra55_iaf'
Submodule 'control/025deg_jra55_ryf' (https://github.com/COSIMA/025deg_jra55_ryf.git) registered for path 'control/025deg_jra55_ryf'
Submodule 'control/1deg_jra55_iaf' (https://github.com/COSIMA/1deg_jra55_iaf.git) registered for path 'control/1deg_jra55_iaf'
Submodule 'control/1deg_jra55_ryf' (https://github.com/COSIMA/1deg_jra55_ryf.git) registered for path 'control/1deg_jra55_ryf'
Submodule 'src/cice5' (https://github.com/COSIMA/cice5.git) registered for path 'src/cice5'
Submodule 'src/libaccessom2' (https://github.com/COSIMA/libaccessom2.git) registered for path 'src/libaccessom2'
Submodule 'src/mom' (https://github.com/mom-ocean/MOM5.git) registered for path 'src/mom'
Submodule 'tools/esmgrids' (https://github.com/DoublePrecision/esmgrids.git) registered for path 'tools/esmgrids'
Submodule 'tools/initial_conditions_access-om2' (https://github.com/COSIMA/initial_conditions_access-om2.git) registered for path 'tools/initial_conditions_access-om2'
Cloning into 'control/01deg_jra55_iaf'...
remote: Enumerating objects: 1800, done.

... lots more output ...

Failed to recurse into submodule path 'src/cice5'

If I manually try to do a pull and then recursively update the git submodules of the partially cloned repository (from the root directory of the access-om2 repo), I get the following error:

[markc@pud190 access-om2]$ git pull
Already up-to-date.
[markc@pud190 access-om2]$ git submodule update --init --recursive
fatal: reference is not a tree: 7309b9b60868357e519eff5aa22e36fc51d94eed
Unable to checkout '7309b9b60868357e519eff5aa22e36fc51d94eed' in submodule path 'src/cice5/ParallelIO'
Failed to recurse into submodule path 'src/cice5'

Where is the specific SHA being set for the ParallelIO  submodule as this seems to be the culprit for the recursive clone not working?

**Comment by aekiss** [comment]
That's odd, a fresh clone works for me (with git v2.30.0, if that matters):

```
~/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE$ git clone --recursive https://github.com/COSIMA/access-om2.git
Cloning into 'access-om2'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 2283 (delta 33), reused 58 (delta 23), pack-reused 2201
Receiving objects: 100% (2283/2283), 912.86 KiB | 349.00 KiB/s, done.
Resolving deltas: 100% (1394/1394), done.
Submodule 'control/01deg_jra55_iaf' (https://github.com/COSIMA/01deg_jra55_iaf.git) registered for path 'control/01deg_jra55_iaf'
Submodule 'control/01deg_jra55_ryf' (https://github.com/COSIMA/01deg_jra55_ryf.git) registered for path 'control/01deg_jra55_ryf'
Submodule 'control/025deg_jra55_iaf' (https://github.com/COSIMA/025deg_jra55_iaf.git) registered for path 'control/025deg_jra55_iaf'
Submodule 'control/025deg_jra55_ryf' (https://github.com/COSIMA/025deg_jra55_ryf.git) registered for path 'control/025deg_jra55_ryf'
Submodule 'control/1deg_jra55_iaf' (https://github.com/COSIMA/1deg_jra55_iaf.git) registered for path 'control/1deg_jra55_iaf'
Submodule 'control/1deg_jra55_ryf' (https://github.com/COSIMA/1deg_jra55_ryf.git) registered for path 'control/1deg_jra55_ryf'
Submodule 'src/cice5' (https://github.com/COSIMA/cice5.git) registered for path 'src/cice5'
Submodule 'src/libaccessom2' (https://github.com/COSIMA/libaccessom2.git) registered for path 'src/libaccessom2'
Submodule 'src/mom' (https://github.com/mom-ocean/MOM5.git) registered for path 'src/mom'
Submodule 'tools/esmgrids' (https://github.com/DoublePrecision/esmgrids.git) registered for path 'tools/esmgrids'
Submodule 'tools/initial_conditions_access-om2' (https://github.com/COSIMA/initial_conditions_access-om2.git) registered for path 'tools/initial_conditions_access-om2'
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/control/01deg_jra55_iaf'...
remote: Enumerating objects: 1800, done.
remote: Counting objects: 100% (1800/1800), done.
remote: Compressing objects: 100% (672/672), done.
remote: Total 6083 (delta 1280), reused 1637 (delta 1128), pack-reused 4283
Receiving objects: 100% (6083/6083), 11.58 MiB | 4.06 MiB/s, done.
Resolving deltas: 100% (4234/4234), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/control/01deg_jra55_ryf'...
remote: Enumerating objects: 294, done.
remote: Counting objects: 100% (294/294), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 1631 (delta 175), reused 199 (delta 84), pack-reused 1337
Receiving objects: 100% (1631/1631), 317.88 KiB | 517.00 KiB/s, done.
Resolving deltas: 100% (1037/1037), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/control/025deg_jra55_iaf'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 977 (delta 63), reused 85 (delta 39), pack-reused 861
Receiving objects: 100% (977/977), 332.67 KiB | 529.00 KiB/s, done.
Resolving deltas: 100% (585/585), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/control/025deg_jra55_ryf'...
remote: Enumerating objects: 301, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (207/207), done.
remote: Total 871 (delta 179), reused 208 (delta 93), pack-reused 570
Receiving objects: 100% (871/871), 197.15 KiB | 384.00 KiB/s, done.
Resolving deltas: 100% (535/535), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/control/1deg_jra55_iaf'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1180 (delta 0), reused 1 (delta 0), pack-reused 1177
Receiving objects: 100% (1180/1180), 588.11 KiB | 672.00 KiB/s, done.
Resolving deltas: 100% (734/734), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/control/1deg_jra55_ryf'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 952 (delta 14), reused 29 (delta 11), pack-reused 916
Receiving objects: 100% (952/952), 339.53 KiB | 526.00 KiB/s, done.
Resolving deltas: 100% (578/578), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/src/cice5'...
remote: Enumerating objects: 298, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 2041 (delta 156), reused 229 (delta 103), pack-reused 1743
Receiving objects: 100% (2041/2041), 62.73 MiB | 5.47 MiB/s, done.
Resolving deltas: 100% (1409/1409), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/src/libaccessom2'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 2455 (delta 9), reused 18 (delta 3), pack-reused 2424
Receiving objects: 100% (2455/2455), 7.93 MiB | 3.21 MiB/s, done.
Resolving deltas: 100% (1514/1514), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/src/mom'...
remote: Enumerating objects: 146, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 44235 (delta 80), reused 112 (delta 56), pack-reused 44089
Receiving objects: 100% (44235/44235), 43.53 MiB | 4.47 MiB/s, done.
Resolving deltas: 100% (16170/16170), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/tools/esmgrids'...
remote: Enumerating objects: 395, done.
remote: Total 395 (delta 0), reused 0 (delta 0), pack-reused 395
Receiving objects: 100% (395/395), 91.36 KiB | 230.00 KiB/s, done.
Resolving deltas: 100% (261/261), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/tools/initial_conditions_access-om2'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 44 (delta 19), reused 36 (delta 12), pack-reused 0
Receiving objects: 100% (44/44), 1.96 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (19/19), done.
Submodule path 'control/01deg_jra55_iaf': checked out '1f956b199fdd3fcf7da83512c6e8818dd76e289a'
Submodule path 'control/01deg_jra55_ryf': checked out 'a018295c2d57bb232ce0ea60b28098de30841afe'
Submodule path 'control/025deg_jra55_iaf': checked out '41c3cc5ac8747e2e3c4efab52cc426bc99aa07d7'
Submodule path 'control/025deg_jra55_ryf': checked out '4e3d7baab6e65105025a38205f224d91e7f9f0c7'
Submodule path 'control/1deg_jra55_iaf': checked out 'c2d22d04e0569e85c0a80180f102f638a0507d21'
Submodule path 'control/1deg_jra55_ryf': checked out '66a8bfb99d36201ac20b7a0033716135a3a5d284'
Submodule path 'src/cice5': checked out '9864af294a659b4b198a39658c1a73514b9300a4'
Submodule 'ParallelIO' (https://github.com/COSIMA/ParallelIO.git) registered for path 'src/cice5/ParallelIO'
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/src/cice5/ParallelIO'...
remote: Enumerating objects: 41346, done.
remote: Total 41346 (delta 0), reused 0 (delta 0), pack-reused 41346
Receiving objects: 100% (41346/41346), 21.90 MiB | 4.07 MiB/s, done.
Resolving deltas: 100% (32047/32047), done.
remote: Enumerating objects: 620, done.
remote: Counting objects: 100% (620/620), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 1945 (delta 614), reused 609 (delta 609), pack-reused 1325
Receiving objects: 100% (1945/1945), 444.07 KiB | 612.00 KiB/s, done.
Resolving deltas: 100% (1362/1362), completed with 131 local objects.
From https://github.com/COSIMA/ParallelIO
 * branch              7309b9b60868357e519eff5aa22e36fc51d94eed -> FETCH_HEAD
Submodule path 'src/cice5/ParallelIO': checked out '7309b9b60868357e519eff5aa22e36fc51d94eed'
Submodule path 'src/libaccessom2': checked out '44e8821ee8484b87a9e6737c0448b356f961266a'
Submodule 'datetime-fortran' (https://github.com/wavebitscientific/datetime-fortran.git) registered for path 'src/libaccessom2/datetime-fortran'
Submodule 'json-fortran' (https://github.com/jacobwilliams/json-fortran.git) registered for path 'src/libaccessom2/json-fortran'
Submodule 'oasis3-mct' (https://github.com/COSIMA/oasis3-mct.git) registered for path 'src/libaccessom2/oasis3-mct'
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/src/libaccessom2/datetime-fortran'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 1093 (delta 34), reused 65 (delta 24), pack-reused 1009
Receiving objects: 100% (1093/1093), 332.43 KiB | 512.00 KiB/s, done.
Resolving deltas: 100% (506/506), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/src/libaccessom2/json-fortran'...
remote: Enumerating objects: 3982, done.
remote: Counting objects: 100% (3982/3982), done.
remote: Compressing objects: 100% (442/442), done.
remote: Total 71084 (delta 3822), reused 3656 (delta 3527), pack-reused 67102
Receiving objects: 100% (71084/71084), 116.74 MiB | 5.76 MiB/s, done.
Resolving deltas: 100% (67329/67329), done.
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/src/libaccessom2/oasis3-mct'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1529 (delta 11), reused 25 (delta 6), pack-reused 1493
Receiving objects: 100% (1529/1529), 16.52 MiB | 3.67 MiB/s, done.
Resolving deltas: 100% (636/636), done.
Submodule path 'src/libaccessom2/datetime-fortran': checked out 'f5310d92bb41f36909d665bbc19869169b2276ac'
Submodule path 'src/libaccessom2/json-fortran': checked out '690a8bd2353fe8256448e6321d462b70e3e9daf8'
Submodule path 'src/libaccessom2/oasis3-mct': checked out '3872880303f8957f716d8ca943d3bfef0fee1c95'
Submodule path 'src/mom': checked out 'af3a94d40f21a4b7fd925d13b928f8721ad7d4c8'
Submodule path 'tools/esmgrids': checked out '9e4b0f22fc962ab7703348e72eceb5042c19994f'
Submodule path 'tools/initial_conditions_access-om2': checked out '98cb2f76a51307d0f39b19471704e716821204e5'
Submodule 'initial_conditions_WOA' (https://github.com/COSIMA/initial_conditions_WOA.git) registered for path 'tools/initial_conditions_access-om2/initial_conditions_WOA'
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/tools/initial_conditions_access-om2/initial_conditions_WOA'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 72 (delta 12), reused 30 (delta 10), pack-reused 38
Receiving objects: 100% (72/72), 9.04 KiB | 3.01 MiB/s, done.
Resolving deltas: 100% (25/25), done.
Submodule path 'tools/initial_conditions_access-om2/initial_conditions_WOA': checked out '1693e4e68b950072527c2629f3e8d1f35e81d7f6'
Submodule 'ocean-ic' (https://github.com/COSIMA/ocean-ic.git) registered for path 'tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic'
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 261 (delta 3), reused 7 (delta 2), pack-reused 251
Receiving objects: 100% (261/261), 279.50 KiB | 471.00 KiB/s, done.
Resolving deltas: 100% (141/141), done.
Submodule path 'tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic': checked out 'dedabdbd191c42c46008b3c1548c444740907fe8'
Submodule 'regridder' (https://github.com/COSIMA/ocean-regrid.git) registered for path 'tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic/regridder'
Cloning into '/Users/andy/Documents/COSIMA/github/COSIMA (OceansAus)/CHUCKABLE/access-om2/tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic/regridder'...
remote: Enumerating objects: 470, done.
remote: Total 470 (delta 0), reused 0 (delta 0), pack-reused 470
Receiving objects: 100% (470/470), 262.60 KiB | 397.00 KiB/s, done.
Resolving deltas: 100% (303/303), done.
Submodule path 'tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic/regridder': checked out 'e3e5404807c05ec4060624dcc0773f419860c8f0'
```

**Comment by MarkCheeseman** [comment]
I am still getting errors with the cice5 git submodules.  I have include the full output from my git clone attempt below:

[markc@pud190 ACCESS]$ git clone --recursive git@github.com:COSIMA/access-om2.git
Cloning into 'access-om2'...
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 2283 (delta 33), reused 58 (delta 23), pack-reused 2201
Receiving objects: 100% (2283/2283), 912.86 KiB | 158.00 KiB/s, done.
Resolving deltas: 100% (1394/1394), done.
Submodule 'control/01deg_jra55_iaf' (https://github.com/COSIMA/01deg_jra55_iaf.git) registered for path 'control/01deg_jra55_iaf'
Submodule 'control/01deg_jra55_ryf' (https://github.com/COSIMA/01deg_jra55_ryf.git) registered for path 'control/01deg_jra55_ryf'
Submodule 'control/025deg_jra55_iaf' (https://github.com/COSIMA/025deg_jra55_iaf.git) registered for path 'control/025deg_jra55_iaf'
Submodule 'control/025deg_jra55_ryf' (https://github.com/COSIMA/025deg_jra55_ryf.git) registered for path 'control/025deg_jra55_ryf'
Submodule 'control/1deg_jra55_iaf' (https://github.com/COSIMA/1deg_jra55_iaf.git) registered for path 'control/1deg_jra55_iaf'
Submodule 'control/1deg_jra55_ryf' (https://github.com/COSIMA/1deg_jra55_ryf.git) registered for path 'control/1deg_jra55_ryf'
Submodule 'src/cice5' (https://github.com/COSIMA/cice5.git) registered for path 'src/cice5'
Submodule 'src/libaccessom2' (https://github.com/COSIMA/libaccessom2.git) registered for path 'src/libaccessom2'
Submodule 'src/mom' (https://github.com/mom-ocean/MOM5.git) registered for path 'src/mom'
Submodule 'tools/esmgrids' (https://github.com/DoublePrecision/esmgrids.git) registered for path 'tools/esmgrids'
Submodule 'tools/initial_conditions_access-om2' (https://github.com/COSIMA/initial_conditions_access-om2.git) registered for path 'tools/initial_conditions_access-om2'
Cloning into 'control/01deg_jra55_iaf'...
remote: Enumerating objects: 1800, done.
remote: Counting objects: 100% (1800/1800), done.
remote: Compressing objects: 100% (672/672), done.
remote: Total 6083 (delta 1280), reused 1637 (delta 1128), pack-reused 4283
Receiving objects: 100% (6083/6083), 11.58 MiB | 2.99 MiB/s, done.
Resolving deltas: 100% (4234/4234), done.
Submodule path 'control/01deg_jra55_iaf': checked out '1f956b199fdd3fcf7da83512c6e8818dd76e289a'
Cloning into 'control/01deg_jra55_ryf'...
remote: Enumerating objects: 294, done.
remote: Counting objects: 100% (294/294), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 1631 (delta 175), reused 199 (delta 84), pack-reused 1337
Receiving objects: 100% (1631/1631), 317.88 KiB | 405.00 KiB/s, done.
Resolving deltas: 100% (1037/1037), done.
Submodule path 'control/01deg_jra55_ryf': checked out 'a018295c2d57bb232ce0ea60b28098de30841afe'
Cloning into 'control/025deg_jra55_iaf'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 977 (delta 63), reused 85 (delta 39), pack-reused 861
Receiving objects: 100% (977/977), 332.67 KiB | 401.00 KiB/s, done.
Resolving deltas: 100% (585/585), done.
Submodule path 'control/025deg_jra55_iaf': checked out '41c3cc5ac8747e2e3c4efab52cc426bc99aa07d7'
Cloning into 'control/025deg_jra55_ryf'...
remote: Enumerating objects: 301, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (207/207), done.
remote: Total 871 (delta 179), reused 208 (delta 93), pack-reused 570
Receiving objects: 100% (871/871), 197.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (535/535), done.
Submodule path 'control/025deg_jra55_ryf': checked out '4e3d7baab6e65105025a38205f224d91e7f9f0c7'
Cloning into 'control/1deg_jra55_iaf'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1180 (delta 0), reused 1 (delta 0), pack-reused 1177
Receiving objects: 100% (1180/1180), 588.11 KiB | 334.00 KiB/s, done.
Resolving deltas: 100% (734/734), done.
Submodule path 'control/1deg_jra55_iaf': checked out 'c2d22d04e0569e85c0a80180f102f638a0507d21'
Cloning into 'control/1deg_jra55_ryf'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 952 (delta 14), reused 29 (delta 11), pack-reused 916
Receiving objects: 100% (952/952), 339.53 KiB | 354.00 KiB/s, done.
Resolving deltas: 100% (578/578), done.
Submodule path 'control/1deg_jra55_ryf': checked out '66a8bfb99d36201ac20b7a0033716135a3a5d284'
Cloning into 'src/cice5'...
remote: Enumerating objects: 298, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 2041 (delta 156), reused 229 (delta 103), pack-reused 1743
Receiving objects: 100% (2041/2041), 62.73 MiB | 13.34 MiB/s, done.
Resolving deltas: 100% (1409/1409), done.
Submodule path 'src/cice5': checked out '9864af294a659b4b198a39658c1a73514b9300a4'
Submodule 'ParallelIO' (https://github.com/COSIMA/ParallelIO.git) registered for path 'ParallelIO'
Cloning into 'ParallelIO'...
remote: Enumerating objects: 41346, done.
remote: Total 41346 (delta 0), reused 0 (delta 0), pack-reused 41346
Receiving objects: 100% (41346/41346), 21.90 MiB | 5.26 MiB/s, done.
Resolving deltas: 100% (32047/32047), done.
fatal: reference is not a tree: 7309b9b60868357e519eff5aa22e36fc51d94eed
Unable to checkout '7309b9b60868357e519eff5aa22e36fc51d94eed' in submodule path 'src/cice5/ParallelIO'
Cloning into 'src/libaccessom2'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 2455 (delta 9), reused 18 (delta 3), pack-reused 2424
Receiving objects: 100% (2455/2455), 7.93 MiB | 3.58 MiB/s, done.
Resolving deltas: 100% (1514/1514), done.
Submodule path 'src/libaccessom2': checked out '44e8821ee8484b87a9e6737c0448b356f961266a'
Submodule 'datetime-fortran' (https://github.com/wavebitscientific/datetime-fortran.git) registered for path 'datetime-fortran'
Submodule 'json-fortran' (https://github.com/jacobwilliams/json-fortran.git) registered for path 'json-fortran'
Submodule 'oasis3-mct' (https://github.com/COSIMA/oasis3-mct.git) registered for path 'oasis3-mct'
Cloning into 'datetime-fortran'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 1093 (delta 34), reused 65 (delta 24), pack-reused 1009
Receiving objects: 100% (1093/1093), 332.43 KiB | 357.00 KiB/s, done.
Resolving deltas: 100% (506/506), done.
Submodule path 'src/libaccessom2/datetime-fortran': checked out 'f5310d92bb41f36909d665bbc19869169b2276ac'
Cloning into 'json-fortran'...
remote: Enumerating objects: 3982, done.
remote: Counting objects: 100% (3982/3982), done.
remote: Compressing objects: 100% (442/442), done.
remote: Total 71084 (delta 3822), reused 3656 (delta 3527), pack-reused 67102
Receiving objects: 100% (71084/71084), 116.74 MiB | 19.15 MiB/s, done.
Resolving deltas: 100% (67329/67329), done.
Submodule path 'src/libaccessom2/json-fortran': checked out '690a8bd2353fe8256448e6321d462b70e3e9daf8'
Cloning into 'oasis3-mct'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1529 (delta 11), reused 25 (delta 6), pack-reused 1493
Receiving objects: 100% (1529/1529), 16.52 MiB | 6.51 MiB/s, done.
Resolving deltas: 100% (636/636), done.
Submodule path 'src/libaccessom2/oasis3-mct': checked out '3872880303f8957f716d8ca943d3bfef0fee1c95'
Cloning into 'src/mom'...
remote: Enumerating objects: 146, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 44235 (delta 80), reused 112 (delta 56), pack-reused 44089
Receiving objects: 100% (44235/44235), 43.53 MiB | 9.84 MiB/s, done.
Resolving deltas: 100% (16170/16170), done.
Submodule path 'src/mom': checked out 'af3a94d40f21a4b7fd925d13b928f8721ad7d4c8'
Cloning into 'tools/esmgrids'...
remote: Enumerating objects: 395, done.
remote: Total 395 (delta 0), reused 0 (delta 0), pack-reused 395
Receiving objects: 100% (395/395), 91.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (261/261), done.
Submodule path 'tools/esmgrids': checked out '9e4b0f22fc962ab7703348e72eceb5042c19994f'
Cloning into 'tools/initial_conditions_access-om2'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 44 (delta 19), reused 36 (delta 12), pack-reused 0
Unpacking objects: 100% (44/44), done.
Submodule path 'tools/initial_conditions_access-om2': checked out '98cb2f76a51307d0f39b19471704e716821204e5'
Submodule 'initial_conditions_WOA' (https://github.com/COSIMA/initial_conditions_WOA.git) registered for path 'initial_conditions_WOA'
Cloning into 'initial_conditions_WOA'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 72 (delta 12), reused 30 (delta 10), pack-reused 38
Unpacking objects: 100% (72/72), done.
Submodule path 'tools/initial_conditions_access-om2/initial_conditions_WOA': checked out '1693e4e68b950072527c2629f3e8d1f35e81d7f6'
Submodule 'ocean-ic' (https://github.com/COSIMA/ocean-ic.git) registered for path 'ocean-ic'
Cloning into 'ocean-ic'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 261 (delta 3), reused 7 (delta 2), pack-reused 251
Receiving objects: 100% (261/261), 279.50 KiB | 350.00 KiB/s, done.
Resolving deltas: 100% (141/141), done.
Submodule path 'tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic': checked out 'dedabdbd191c42c46008b3c1548c444740907fe8'
Submodule 'regridder' (https://github.com/COSIMA/ocean-regrid.git) registered for path 'regridder'
Cloning into 'regridder'...
remote: Enumerating objects: 470, done.
remote: Total 470 (delta 0), reused 0 (delta 0), pack-reused 470
Receiving objects: 100% (470/470), 262.60 KiB | 346.00 KiB/s, done.
Resolving deltas: 100% (303/303), done.
Submodule path 'tools/initial_conditions_access-om2/initial_conditions_WOA/ocean-ic/regridder': checked out 'e3e5404807c05ec4060624dcc0773f419860c8f0'
Failed to recurse into submodule path 'src/cice5'

It's the ParallelIO submodule that is not being resolved properly.  Are there permission restrictions on this repo?

[markc@pud190 ACCESS]$ ls access-om2/src/cice5
bld   cicedoc  csm_share  drivers          io_binary  io_pio    mpi       ParallelIO  README_v5.1  solo_ice_comp
cice  compile  doc        input_templates  io_netcdf  Makefile  namelist  README.md   serial       source
[markc@pud190 ACCESS]$ ls access-om2/src/cice5/ParallelIO/
[markc@pud190 ACCESS]$

**Comment by aekiss** [comment]
Thanks for the extra details @MarkCheeseman.

The ParallelIO submodule points to commit 7309b9b but that isn't in the the repo.
https://github.com/COSIMA/ParallelIO/commit/7309b9b60868357e519eff5aa22e36fc51d94eed says:
```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```

@nichannah can you have look at this please?

**Comment by nichannah** [comment]
This should be fixed.

**Comment by MarkCheeseman** [comment]
I can successfully check out all the git submodules now.  Thanks @nichannah !

**Comment by aekiss** [comment]
I've also updated the control submodules to use the latest cice executable.

To update a previous clone of this repository to the latest version, you will need to do
```
git pull
git submodule update --init --recursive
```
to update all the submodules.
