### ISSUE TITLE
Stability of ACCESS-OM2-01 run with large biharmonic lateral viscosity

### ISSUE THREAD

**Issue by rmholmes** [COSIMA/access-om2#232]
I am trying to run ACCESS-OM2-01 with a lateral viscosity coefficient that is equivalent to ACCESS-OM2-025. The hypothesis being that an increase in horizontal resolution *without* changes in viscosity will lead to much reduced spurious mixing.

Using the scaling from Griffies and Hallberg (2000, MWR) for the Smagorinsky biharmonic friction I have changed `k_smag_iso` from 2 to 7.9 (to get equivalent viscosity to ACCESS-OM2-025) and initialized a run from `restart635` of Andy's ACCESS-OM2-01 RYF run with `k_smag_iso=7.9`.  However, perhaps unsurprisingly I'm running into stability issues.

I understand (see Griffies and Hallberg, Section 2c) that there is a diffusive time step limit and so I may need to reduce the time step. I have been able to run sucessfully for six-months (2 submits) with dt=300s (compared to previous 540s), which is encouraging. However, in the 3rd submit it fails with `free surface penetrating rock` after one month. The problem is that if I try to further reduce the time step the model seems to fail earlier than this (usually with `temp` or `salt` `out of range`). I've tried all available time steps down to 100s.

Does anyone have any suggestions/hints on how to get around this? Why does reducing the time step make things worse? Perhaps I need to slowly build up the viscosity rather than changing it in one go? Any help would be much appreciated.

**Comment by rmholmes** [comment]
The run is located here if anyone wants a look:
`/home/561/rmh561/access-om2/01deg_jra55_ryf_k_smag_iso7p9`
`/scratch/e14/rmh561/access-om2/archive/01deg_jra55_ryf_k_smag_iso7p9`

**Comment by russfiedler** [comment]
I can't see that project but have you checked the excessive friction reports? Look for lines with ` exceeds max value` and/or `violations per pe are`. These are just warnings. As for the earlier detection of range violations I think this is just a case that the range is only checked every `diag_steps` timesteps. If you drop the time step it gets noticed earlier in model time

**Comment by russfiedler** [comment]
@rmholmes  The viscosities should be automatically limited to less than the linear stabilty limit. You might want to output the variable `visc_crit` along with `aiso_smag` (maybe just the max value over a period) to see how close to the limit you are getting.

Note also the namelist variable `visc_scale_limit`. You can knock down the allowable maximum but still have your larger viscosity in general
https://github.com/mom-ocean/MOM5/blob/af3a94d40f21a4b7fd925d13b928f8721ad7d4c8/src/mom5/ocean_param/lateral/ocean_bihgen_friction.F90#L93-L99

**Comment by rmholmes** [comment]
Thanks @russfiedler!! I didn't know there was an automatic limiter. However, after a more careful look through the .out file I don't think I'm hitting these limits - I don't see warnings like that and the "Excessive horizontal biharmonic friction summary" sections are empty.

Probably the increased viscosity is changing the flow such that I start running into other problems. I am getting rather large velocities in the Arctic (probably estuaries like always). E.g.:
```
u (  6.43     m/s) is   62.98 % of CFL (  10.2     m/s) at (i,j,k) = (3223,2617, 34), (lon,lat,thk) = (      68.176,      77.125,   269.877 m)
 where grid is (m) (dxu,dyu,dzu) = (   0.307E+04,   0.351E+04,     5.783
v ( -8.09     m/s) is   54.64 % of CFL (  14.8     m/s) at (i,j,k) = (2507,2124, 42), (lon,lat,thk) = (     -29.307,      65.633,   605.492 m)
6186 where grid is (m) (dxu,dyu,dzu) = (   0.459E+04,   0.444E+04,    12.718
```
Compared to max's of ~1.5ms-1 (~25% of CFL) in the standard run.

I don't think the range violations I get when I decrease the time step are because of `diag_steps`. When I decrease the time step it errors very quickly (3 mins into run, no output beyond pre-amble into `access-om2.out`), whereas with 300s it gets at least a month in.

I've given you access to e14 - I'm sick of these permissions issues. I hope that is ok.

I will put some more detective work into those arctic regions tomorrow.

**Comment by russfiedler** [comment]
@rmholmes  Yeah, it looks like the flow around the north of Severny Island has changed completely. It seems that it used to flow around it, hugging the coast/shelf and now it peels off and there's an unresolved overflow that may be causing problems.

Hang on. Those high CFL values for `U`are right where some edits were made in late 2018 to the bathymetry for stability reasons. See `/g/data/hh5/tmp/cosima/bathymetry/topog_23_10_2018_severny.txt`. Topography checksums look ok though so no problems there.

**Comment by rmholmes** [comment]
Thanks @russfiedler, and sorry for the slow response.

I guess adding Rayleigh drag would be a reasonable way to deal with this? I am not too worried about hacking with my solution too much. I will give it a go.

I'm still confused as to why lowering the time step seems to cause other problems. But in any case, it can't be a good thing to have 8ms-1 velocities even if the time step can be lowered to deal with them.

**Comment by russfiedler** [comment]
@rmholmes  I had a look at your new table. The thing that strikes me is that the damping doesn't extend to the sea floor which is a bit weird especially since it's so strong (3hrs). I've created a version which is a bit more sensible I think. See (no sniggering, please) `/scratch/v45/raf599/drag/field_table_clean_bottom`. This should also get rid of over 500 warnings like `==>Warning ocean_momentum_source_init: ignored nonzero rayleigh_damp_table(3225,2613,   9) set over land. Is your table correct?`

**Comment by rmholmes** [comment]
Thanks @russfiedler. I hadn't noticed that I hadn't extended the damping to the seafloor (just copied the KaraStr stuff that Andrew put in). I knew there were warnings there but good to avoid.

I'll have another go with your new table. However, I think I'm going to be fighting spot fires with this run for a while... The first time I ran with my new additions to the field_table it still crashed - this time with a salinity out of range error in a narrow strait north of Hudson Bay.

**Comment by aekiss** [comment]
here's a script to check that the damping is where you want it to be and extends to the seafloor
https://github.com/COSIMA/topogtools/blob/master/Rayleigh_drag.ipynb

**Comment by russfiedler** [comment]
@rmholmes I had a bit of a look at your restart files to see if I could spot anything. Severny island is in file 24 with local coordinates approx (335,460). Starting below about level 34 you can see problems starting at the coast ad things becoming crazy at level 36/37. Having a look at `dzt` at global coordinates (3223,2617) we see some partial cells about 7m thick compared to about 35m. My guess is that there's some sort of nasty interaction happening. There's an option in the biharmonic friction module to revert to laplacian along the bottom which you aren't using. It's meant for very thin cell by the looks but it could be worth looking at.

**Comment by rmholmes** [comment]
Thanks @russfiedler. I presume you're talking about `bottom_5point`? It's worth a shot!

I've been making progress by adding Rayleigh drag in the spots where issues creep up (I'm up to about 4 different spots now). I've progressed it forward by over a month using that system - so I'm hopeful I'll get there in the end.

**Comment by russfiedler** [comment]
Yes, that's what I'm referring to. Hopefully you can one shot this (with a judicious choice of parameters) rather than playing whack-a-mole. I really dislike the Rayleigh drag approach especially when it's applied as a constant time scale all the way to the surface when the problem appears to be confined to the bottom few cells.

**Comment by rmholmes** [comment]
I decided for now not to go with the `bottom_5point` option. This will potentially change things everywhere in the bottom layer - and I don't really want to do that for this run (numerical mixing is quite prominent near topography). I'm happy to just fight spot-fires here. I'm up to about 5 different spots - and if these spots aren't near the coastline then I'm restricting the Rayleigh drag to the deep cells only.

I was up to almost 3 years (I plan to do 5), with no problems for the previous 2. However, I've now run into a CICE error that I haven't seen before - and I can't identify where it's coming from. I've rerun once to confirm it's reproducible.

The errors are:
`access-om2.err`:
```
[gadi-cpu-clx-0790:518994:0:518994] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[gadi-cpu-clx-0790:518994:0:518994] ib_mlx5_log.c:139  DCI QP 0x2c289 wqe[591]: SEND s-e [rqpn 0x2fa30 rlid 3192] [inl len 58]
...
=================================
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source
cice_auscom_3600x  000000000089E594  Unknown               Unknown  Unknown
...
```

In the CICE logs I have a bunch of lines with `Repeat ridging, niter =           1`.

Is there an easy way to identify where this error is coming from without rerunning? Otherwise, I would plan to rerun with a higher frequency `diag_step` and identify where the high velocities that directly cause the issue are coming from using the ocean .out CFL info. Once again, the run is at `/home/561/rmh561/access-om2/01deg_jra55_ryf_k_smag_iso7p9/` or `/scratch/e14/rmh561/access-om2/archive/01deg_jra55_ryf_k_smag_iso7p9/`

Thanks!

**Comment by aekiss** [comment]
That's an MPI error I believe - I get these occasionally, something to do with comms on the machine. They tend to come in bunches and then resolve themselves. Try rerunning a few more times.

**Comment by aekiss** [comment]
Is it listed in your `resub.sh`? If so, try increasing `MAX_RESUBMISSIONS` to have payu do the resubmission for you. You'll also need this at the end of your `config.yaml`
```
userscripts:
    error: resub.sh
    run: rm -f resubmit.count
```

You can also look at the resubmission log `resubmit.log` to see how often this is happening.

**Comment by rmholmes** [comment]
Thanks @aekiss. These are older configs so there is no resubmission setup. I've set it up now.

The presence of lots of `diag_manager` velocity out of range warnings also made me think it was a model error not an MPI issue. But I'll try again.

**Comment by rmholmes** [comment]
Success. Thanks Andrew. Rerunning once only was clearly not enough.

**Comment by rmholmes** [comment]
I've successfully completed this run and got what I need. Closing the ticket.
