### ISSUE TITLE
ACCESS-OM2 crashes at the end of September when ktherm=2 in CICE

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/access-om2#239]
this is a question for @aekiss and others who use different settings for CICE.

when i set `ktherm = 2` in `cice_in.nml`, my simulation crashes at the end of September, according to `access-om2.out` which ends with the following output:

```
                                                             Land cell summary:

 Locations (if any) where land cell velocity is non-zero...

yyyy/mm/dd hh:mm:ss = 1904/ 9/28  0: 0: 0
 Maximum zonal Re = 1.99E+02 at (i,j,k) = ( 149, 136,  14), (lon,lat,dpt) = (-131.00,  -0.33,  98.05), U = 1.14E+00, mix = 0.78E+13
 Maximum merid Re = 2.35E+01 at (i,j,k) = ( 264, 271,   1), (lon,lat,dpt) = ( -17.33,  76.82,   1.15), V =-5.14E-01, mix = 0.28E+13
 Kinetic energy (Joules)                          =   0.754747717668E+18
```
It is interesting that I don't get this error if I stop the run at the end of August and restart from September 1. I just cannot run the model continuously for a year (Jan 1 - Dec 31). This does not happen when `ktherm=1`.

Has anyone experienced this? Any idea?

My experiment is located: `/scratch/v45/hh0162/access-om2-iamip2/control/1deg_jra55_ryf_iamip2_sen5`

**Comment by aekiss** [comment]
Interesting. `/scratch/v45/hh0162/access-om2-iamip2/control/1deg_jra55_ryf_iamip2_sen5/work/ice/ice.log.task_0015` says 
```
 preflushing: fbri <= c0:          16         237
 vicen, aicen  2.186980265810437E-005  9.770230490606442E-005
 fbri, hice_old  0.000000000000000E+000  0.297064785440954
```
...not sure what that means though...

**Comment by aekiss** [comment]
you also need to set `tfrz_option='mushy'` - maybe that will help?

**Comment by aekiss** [comment]
looks like cice aborted here: https://github.com/COSIMA/cice5/blob/dfb833ad/source/ice_brine.F90#L182-L187

**Comment by hakaseh** [comment]
@aekiss thanks for looking into this and identifying the issue. i guess the brine fraction is less than some threshold value, but i really don't know what it means. i just set `tfrz_option='mushy'`, and re-submitted the job for 1 year. hopefully this fixes the issue.

**Comment by hakaseh** [comment]
@aekiss the run was successful, so i think the issue was that I did not set `tfrz_option='mushy'`. 

thanks again and i will close the issue.

**Comment by ofa001** [comment]
Hi Hakese,  Andrew,

Yes it looks like you have switched on the mushy option ktherm=2  and not switched some of the other options as well, did you want the mush physics on it looks like you are only using the 1 degree version   and Andrew only ran it for the 0.1degree set up after encountering an instability over low salinity cases ,  There is a fix for that in our coupled code (via the met office).


The mushy option though would be the approach  if you are looking at any of the CICE BGC code.


Siobhan

**Comment by hakaseh** [comment]
I had to re-open the issue because my run with cold restart gave the same error although i set `tfrz_option = 'mushy'`.

@ofa001 are there any other options I need to change if I want to use `ktherm=2`? could you tell me how you fixed it?

we have the CICE BGC turned on and are testing different options, one of which is mushy layer.

**Comment by hakaseh** [comment]
An update that the issue was resolved by reducing the time step to 3600s (from 5400s).
