### ISSUE TITLE
UCX warning messages filling log file

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/access-om2#244]
Currently the `access-om2.out` stdout log file has a large number of lines (10425 for a 1 degree model, 278504 for a 0.1 degree model) like this:
```
[1628734843.363293] [gadi-cpu-clx-0929:1129006:0]          mpool.c:38   UCX  WARN  object 0x12334480 was not returned to mpool ucp_requests
```

These may be due to not waiting for non-blocking requests to return (https://github.com/open-mpi/ompi/issues/6376), but in any case are only warnings, and can be ignored. 

They can be suppressed by setting an environment variable: `UCX_LOG_LEVEL=error`

This should be done for all the configs by adding this to `config.yaml`
```yaml
env:
    UCX_LOG_LEVEL: 'error'
```

**Comment by aekiss** [comment]
should I do this or are you onto it?

**Comment by aidanheerdegen** [comment]
Not currently doing it. Just flagged for it to be done.

Aside: I usually try and assign issues to me if I am working on them so as not to duplicate effort ... speaking of which ... <exits left to assign himself to issues currently working on>

**Comment by aekiss** [comment]
@aidanheerdegen if these PRs look OK, feel free to merge

**Comment by aekiss** [comment]
(sorry for barging in with this, I just realised I hadn't read your reply carefully)

**Comment by aidanheerdegen** [comment]
No barging. I hadn't planned on doing it myself ...

**Comment by aidanheerdegen** [comment]
Travis is being a pain. Will need to merge without CI, see https://github.com/COSIMA/access-om2/issues/245.

Sorry, I realise I quoted error, but when I actually tested it I didn't use quotes. My apologies.
```yaml
env:
  UCX_LOG_LEVEL: error
```
http://www.yamllint.com says it's ok and functionally the same. I have now tested with quotes and it also works fine.

**Comment by aekiss** [comment]
no worries @aidanheerdegen - if the quotes are just a cosmetic issue I think we'll cope
