### ISSUE TITLE
Explicitly set CICE diagnostic flags

### ISSUE THREAD

**Issue by aekiss** [COSIMA/access-om2#250]
Following on from https://github.com/COSIMA/1deg_jra55_iaf/issues/9:
These 103 diagnostics are set to `'m'` by default in the cice code in [ice_history_mechred.F90](https://github.com/COSIMA/cice5/blob/master/source/ice_history_mechred.F90), [ice_history_pond.F90](https://github.com/COSIMA/cice5/blob/master/source/ice_history_pond.F90) and (most of them) [ice_history_shared.F90](https://github.com/COSIMA/cice5/blob/master/source/ice_history_shared.F90)
```
f_ardg      = 'm'
f_vrdg       = 'm'
f_alvl      = 'm'
f_vlvl       = 'm'
f_dardg1dt  = 'm'
f_dardg2dt   = 'm'
f_dvirdgdt  = 'm'
f_opening    = 'm'
f_apondn    = 'm'
f_apeffn     = 'm'
f_hpondn    = 'm'
f_hi        = 'm'
f_hs         = 'm'
f_Tsfc      = 'm'
f_aice       = 'm'
f_uvel      = 'm'
f_vvel       = 'm'
f_uatm      = 'm'
f_vatm       = 'm'
f_fswdn     = 'm'
f_flwdn      = 'm'
f_fswup     = 'm'
f_snow      = 'm'
f_snow_ai    = 'm'
f_rain      = 'm'
f_rain_ai    = 'm'
f_sst       = 'm'
f_sss        = 'm'
f_uocn      = 'm'
f_vocn       = 'm'
f_sice      = 'm'
f_frzmlt     = 'm'
f_fswfac    = 'm'
f_fswabs    = 'm'
f_fswabs_ai  = 'm'
f_albsni    = 'm'
f_alvdr_ai  = 'm'
f_alidr_ai   = 'm'
f_alvdf_ai  = 'm'
f_alidf_ai   = 'm'
f_albice    = 'm'
f_albsno     = 'm'
f_albpnd    = 'm'
f_coszen     = 'm'
f_flat      = 'm'
f_flat_ai    = 'm'
f_fsens     = 'm'
f_fsens_ai   = 'm'
f_flwup     = 'm'
f_flwup_ai   = 'm'
f_evap      = 'm'
f_evap_ai    = 'm'
f_Tair      = 'm'
f_Tref      = 'm'
f_Qref       = 'm'
f_congel    = 'm'
f_frazil     = 'm'
f_snoice    = 'm'
f_dsnow      = 'm'
f_meltt     = 'm'
f_melts      = 'm'
f_meltb     = 'm'
f_meltl      = 'm'
f_fresh     = 'm'
f_fresh_ai   = 'm'
f_fsalt     = 'm'
f_fsalt_ai   = 'm'
f_fhocn     = 'm'
f_fhocn_ai   = 'm'
f_fswthru   = 'm'
f_fswthru_ai = 'm'
f_strairx   = 'm'
f_strairy    = 'm'
f_strtltx   = 'm'
f_strtlty    = 'm'
f_strcorx   = 'm'
f_strcory    = 'm'
f_strocnx   = 'm'
f_strocny    = 'm'
f_strintx   = 'm'
f_strinty    = 'm'
f_strength  = 'm'
f_divu      = 'm'
f_shear      = 'm'
f_sig1      = 'm'
f_sig2       = 'm'
f_dvidtt    = 'm'
f_dvidtd     = 'm'
f_daidtt    = 'm'
f_daidtd     = 'm'
f_dagedtt   = 'm'
f_dagedtd    = 'm'
f_mlt_onset = 'm'
f_frz_onset  = 'm'
f_iage      = 'm'
f_FY         = 'm'
f_hisnap    = 'm'
f_aisnap     = 'm'
f_trsig     = 'm'
f_icepresent = 'm'
f_fsurf_ai  = 'm'
f_fcondtop_ai= 'm'
f_fmeltt_ai = 'm'
```
of these, the following are not explicitly defined in `cice_in.nml` in any of the standard ACCESS-OM2 configs, and are therefore always output monthly (except for `f_dagedtt`, `f_dagedtd` - see below)
```
f_uatm
f_vatm
f_fswup
f_alvdr_ai
f_alidr_ai
f_alvdf_ai
f_alidf_ai
f_dagedtt
f_dagedtd
```
So it would be a good idea to explicitly set these in `cice_in.nml`.

Then the question is, should we set them to `'m'` to match the current behaviour? Or should they be `'x'` since nobody explicitly asked for them and it would save space?

**Comment by aekiss** [comment]
Actually `f_dagedtt`, `f_dagedtd` are set to `'x'` by default since we have `tr_iage` = false
`f_FY` is  set to `'x'` by default since we have `tr_fy` = false
see https://github.com/COSIMA/cice5/blob/2572851d/source/ice_history.F90#L142-L147

**Comment by hakaseh** [comment]
@aekiss can I add the missing diags in `master` of the 6 configs (e.g. https://github.com/COSIMA/01deg_jra55_iaf/tree/master), as I did for Cycle 4 (https://github.com/COSIMA/01deg_jra55_iaf/commit/d4859bcb58ed45475d95dc89a0c45a4ecd05c120)? Then, I should be able to simply merge `master` into `master+bgc` to reflect these changes into `master+bgc`. This will half the amount of work required (instead of modifying 6 configs x 2 branches).

**Comment by aekiss** [comment]
I have some other things that need fixing in the `master` branches so it would be better to make the changes in `master+bgc` and I'll merge them into `master` later. Thanks!

**Comment by hakaseh** [comment]
Ok I will update `master+bgc`

Regards,
Hakase
________________________________

**Comment by hakaseh** [comment]
I just finished adding missing diags in all of the 6 `master+bgc` configs (e.g. https://github.com/COSIMA/01deg_jra55_iaf).

**Comment by aekiss** [comment]
great, thanks!

**Comment by aekiss** [comment]
closing - this has now been done in all the standard configs
