### ISSUE TITLE
how to calculate ‘msftyzmpa’ from MOM outputs

### ISSUE THREAD

**Issue by ars599** [COSIMA/access-om2#259]
Dear all,

I have a CMIP6 inquire from UC Riverside and they are looking for the eddy-induced MOC in the Southern Ocean, and would like to have msftyzmpa. 
I would like to know how to calculate this term from MOM? I guess that will be great to promote both ACCESS coupled model and also the OM2 outputs.

Regards,

Arnold

**Comment by rmholmes** [comment]
Hi Arnold,

This should be just the zonal sum (along the `xt_ocean` dimension) of the `ty_trans_gm` diagnostic from the MOM output. This diagnostic is already cumulatively integrated in the vertical direction.

Cheers,

Ryan

**Comment by ars599** [comment]
Many thanks Ryan!! I will give a try.
