### ISSUE TITLE
Fix land mask around Antarctic coast for 0.25deg topography

### ISSUE THREAD

**Issue by micaeljtoliveira** [COSIMA/access-om2#265]
This issue was first discussed [here](https://github.com/COSIMA/access-om2/issues/158). More details in this [comment](https://github.com/COSIMA/access-om2/issues/158#issuecomment-971064268) and comments following.

The proposed solution is:

> We decided that the way forward is to change the land mask for the Antarctic coast (and nowhere else) to match GEBCO 2014, which will convert some ocean regions to land, but also convert some land to ocean, which will change the number of active tiles and may require tweaks to remove non-advective cells.

**Comment by micaeljtoliveira** [comment]
I've used the [topog2mask.py](https://github.com/COSIMA/topogtools/blob/master/topog2mask.py) script in [topogtools](https://github.com/COSIMA/topogtools) to create a mask from the GEBCO 2014 topography. Here is the old (left) versus new masks (right):
![masks](https://user-images.githubusercontent.com/12744925/187101354-5a399d81-08c2-4dac-a985-5f97407c3524.png)

The differences look reasonable (red means new land, blue means new water):
![mask_diff](https://user-images.githubusercontent.com/12744925/187101485-22fbaa47-574a-4011-8aa2-ff5c916ea8bf.png)

Considering that the grid extends beyond 80º S, I would say that there's no need to extend it any further, as they don't seem to be any changes to the mask further south.

@aekiss Does this look reasonable to you?

**Comment by aekiss** [comment]
Great that the grid doesn't need extending.

Currently the minimum x-size of the grid is 6km, occurring at the Antarctic margin. Can you tell from the grid data how much smaller dx will be if we move the coastline further south? We don't want it too small, as it may reduce the maximum timestep we can use while avoiding CFL instability (particularly "remap transport: bad departure points" errors in CICE).

Do you know if extending the ocean further south will require 1 more row of tiles, or will it need more?

The top 2 plots are partly obscured by the filled coastline data, making it hard to see the changes. Could they be replotted with only the model data displayed?

It looks like this removes some land at the tip of the Antarctic Peninsula and adds and removes some islands to the west of the Antarctic Peninsula? This would be clearer if the regions that are land in both old and new masks were plotted in a different colour.

It looks like this also fixes a glitch in the coastline at 0° longitude?

**Comment by ofa001** [comment]
Yes @aekiss and @micaeljtoliveira  a little worried at what is occurring with the blue around the tip of peninsula are a lot of islands  being removed.  I guess I said for the large ice shelves (Ross Ronnie/Filchner  they probably had originally  very straight  edges when in reality they are more complex like in the new topography.

**Comment by micaeljtoliveira** [comment]
> Currently the minimum x-size of the grid is 6km, occurring at the Antarctic margin. Can you tell from the grid data how much smaller dx will be if we move the coastline further south? We don't want it too small, as it may reduce the maximum timestep we can use while avoiding CFL instability (particularly "remap transport: bad departure points" errors in CICE).

I'll calculate this and let you know.

> Do you know if extending the ocean further south will require 1 more row of tiles, or will it need more?

No yet. I first need to combined the new mask with the old one, as we only want the changes from the new mask in the Antarctic region.

> The top 2 plots are partly obscured by the filled coastline data, making it hard to see the changes. Could they be replotted with only the model data displayed?

Here they are:
![masks2](https://user-images.githubusercontent.com/12744925/187111363-e5f78faf-da89-4eb5-b977-d6b482064375.png)

> It looks like this removes some land at the tip of the Antarctic Peninsula and adds and removes some islands to the west of the Antarctic Peninsula? This would be clearer if the regions that are land in both old and new masks were plotted in a different colour.

Yes, it seems there are quite some changes around the Antarctic Peninsula. Here is the new plot:
![changes](https://user-images.githubusercontent.com/12744925/187111411-b5636166-00a2-41be-8d4a-b63868bbf925.png)

 
> It looks like this also fixes a glitch in the coastline at 0° longitude?

The glitch seems to be coming from the old mask. I would say the new mask looks better in that area.

**Comment by aekiss** [comment]
Thanks, those plots are great.
Might be worth (visually) comparing to the 0.1deg land mask to see what choices @russfiedler made, particularly at the end of the peninsula.

**Comment by micaeljtoliveira** [comment]
@aekiss The new value for dx is approx. 5.5 km, corresponding to a new southernmost latitude of -78.65.

I've also plotted the 0.1deg land mask (right figure bellow). I'm not sure what to make out of it.

![01_02_masks](https://user-images.githubusercontent.com/12744925/187345660-94c04139-7c23-4104-ad84-c8bbc8e1db56.png)

**Comment by aekiss** [comment]
Hmm, the old 0.25 mask looks more like the 0.1 mask at the end of the peninsula than the new 0.25 mask does. ie the old mask looks "better" there.

I'm guessing there's a mix of deep water and low-altitude ice shelves/land on the GEBCO grid, which averages to something below sea level when regridded to the 0.25 grid. In this situation it may be more valid to treat a 0.25 grid cell as land if it contains any land on the GEBCO grid.

Probably the simplest thing to do would be retain the old 0.25 mask everywhere north of 65S.

**Comment by adele157** [comment]
Keeping the old mask north of 65S seems a bit arbitrary. 

I think testing something more reproducible would be better (e.g. the suggestion 'to treat a 0.25 grid cell as land if it contains any land on the GEBCO grid').

**Comment by aekiss** [comment]
That could be done by basing the land mask on the `frac` (rather than `depth`) field in `topg_new.nc` (as output by [gen_topo.f90](https://github.com/COSIMA/topogtools/blob/master/gen_topo.f90)), i.e. setting all points with `frac < 1` to land.

**Comment by micaeljtoliveira** [comment]
> That could be done by basing the land mask on the frac (rather than depth) field in topg_new.nc (as output by [gen_topo.f90](https://github.com/COSIMA/topogtools/blob/master/gen_topo.f90)), i.e. setting all points with frac < 1 to land.

That should be straightforward to implement. Let me try it and see how it looks.

**Comment by aekiss** [comment]
![Screen Shot 2022-08-30 at Tue 30-8 3 16pm](https://user-images.githubusercontent.com/31054815/187355295-6fd48356-ac7b-407c-a112-ad46e20bd0aa.png)

**Comment by aekiss** [comment]
maybe too much land now

**Comment by aekiss** [comment]
here's frac < 0.8
![Screen Shot 2022-08-30 at Tue 30-8 3 19pm](https://user-images.githubusercontent.com/31054815/187355636-fe0673eb-f300-4f5c-9555-3e5cbcdd46e9.png)

**Comment by aekiss** [comment]
it starts to get a bit arbitrary

**Comment by micaeljtoliveira** [comment]
Yes, that's a bit arbitrary. Plus, it's not clear how it will impact the mask in other areas.

**Comment by aekiss** [comment]
Here's frac <0.5. I think this looks closest to the 0.1deg mask. There will be quite a few non-advective points to remove.
![Screen Shot 2022-08-30 at Tue 30-8 3 23pm](https://user-images.githubusercontent.com/31054815/187356198-e7273a8a-e3bf-4cb2-96f8-cb7eec0d5c3f.png)

**Comment by aekiss** [comment]
here's the whole coastline with frac<0.5 (click to enlarge)
![Screen Shot 2022-08-30 at Tue 30-8 3 28pm](https://user-images.githubusercontent.com/31054815/187356783-64057e8d-e2f0-4164-919f-d509c0da7986.png)

**Comment by aekiss** [comment]
setting frac<0.5 seems somehow less arbitrary than any other value, and seems to do a good enough job - it's be interesting to see what an updated [difference plot](https://user-images.githubusercontent.com/12744925/187111411-b5636166-00a2-41be-8d4a-b63868bbf925.png) would look like with this mask.

**Comment by adele157** [comment]
Great, let's use 0.5!

**Comment by aekiss** [comment]
Actually, to be certain we won't have any ocean points with depth above sea level, we need to set land to `(frac < 0.5) AND (depth <= 0.0)` in https://github.com/COSIMA/topogtools/blob/master/topog2mask.py#L31

**Comment by micaeljtoliveira** [comment]
@aekiss Shouldn't the condition be `(frac < 0.5) OR (depth <= 0.0)`? 

If I understood the issue correctly, the problem is that some points that have `depth > 0` and `frac < 0.5`, but are being marked as ocean, while we would like them to be marked as land. To do this, we must mark as land any points that have `depth <= 0` OR `frac < 0.5`, no?

Anyway, the condition  `(frac < 0.5) AND (depth <= 0.0)` leaves the new mask unchanged, while the OR condition yields the following new mask (left), which looks quite similar to the one from the 0.1deg topography (right):

![new_mask_comp](https://user-images.githubusercontent.com/12744925/187592531-b850dfe0-7e8b-446d-8ed2-b98baa2cef4c.png)

And here is the plot showing the changes wrt the old mask:

![new_mask_diff](https://user-images.githubusercontent.com/12744925/187592600-15fd45f2-9e30-410f-a62b-843d2650af7f.png)

I would say we are on the right track!

**Comment by adele157** [comment]
Looks great!

**Comment by aekiss** [comment]
Oops, yes you're absolutely right re. using OR rather than AND. The new mask looks excellent. 

Next step is to fix non-advective points in the mask.
They can be found with [non-advective.ipynb](https://github.com/COSIMA/topogtools/blob/master/non-advective.ipynb) and fixed with [editTopo.py](https://github.com/COSIMA/topogtools/blob/master/editTopo.py).
If I recall correctly it might also be possible to do some of this automatically with [fix_nonadvective_mosaic.f90](https://github.com/COSIMA/topogtools/blob/master/fix_nonadvective_mosaic.f90). It might not pick up all of them but could clean up most of them more easily.

**Comment by micaeljtoliveira** [comment]
Looks like there are quite a lot of new nonadvective cells (>200!). I tried using [fix_nonadvective_mosaic.f90](https://github.com/COSIMA/topogtools/blob/master/fix_nonadvective_mosaic.f90), but it doesn't seem to work properly, as the python notebook still identifies the same nonadvective before and after "fixing" those cells.

**Comment by micaeljtoliveira** [comment]
[fix_nonadvective_mosaic.f90](https://github.com/COSIMA/topogtools/blob/master/fix_nonadvective_mosaic.f90) also seems to have a strange side effect when used on top of the new mask. After "fixing" the advective cells with the tool, some ocean cells now have a height of zero, which should definitely not happen (took me most of the day to realize it was the tool that was doing this, not my new mask... :disappointed:

**Comment by russfiedler** [comment]
@micaeljtoliveira  I have vague memories of a (logic) bug in old versions of this code. I'll have a hunt around and see where/when it was fixed.  Can you point me to the location of the topogrhy files in question or put them in a public place and I'll see what is going on?

**Comment by aekiss** [comment]
@russfiedler is `fix_nonadvective_mosaic.f90` designed to work on mask files, or only topography?

**Comment by aekiss** [comment]
@micaeljtoliveira [non-advective.ipynb](https://github.com/COSIMA/topogtools/blob/master/non-advective.ipynb) is overzealous, so you probably won't need to remove all the non-advective points it identifies. Only the points with no advective connection to the ocean need to be removed.

**Comment by russfiedler** [comment]
@aekiss  Only on topography. It infers the mask from the topography file (topog<=0.0)

**Comment by aekiss** [comment]
Thanks @russfiedler and apologies @micaeljtoliveira for giving you a bad suggestion.

**Comment by micaeljtoliveira** [comment]
@russfiedler My topography files are here: `/g/data/v45/mo1833/topography/make_025deg_topo`. This folder is a clone of https://github.com/COSIMA/make_025deg_topo with a single modification: I'm calling a script to modify the land mask before it is applied to the topography. The topography after applying the mask is the `topog_new_edited_deseas_partialcell_mindepth_masked.nc` file and `topog_new_edited_deseas_partialcell_mindepth_masked_fixnonadvective.nc` is the topography after calling `fix_nonadvective_mosaic.f90`.

I didn't check this in detail, but after thinking a bit more about what is going on, my guess is that the tool is creating some new land to fix the nonadvective cells.

@aekiss No worries, I'm still learning quite a lot with all these issues ;)

**Comment by russfiedler** [comment]
@micaeljtoliveira  Yes, your suspicions are correct. There's definitely land being created to eliminate non advective cells. The regions I looked at seemed ok to me.

**Comment by micaeljtoliveira** [comment]
@russfiedler Thanks for looking into this. After discussing further with @aekiss we decided that the best would be to fix most of these non-advective cells at the level of the mask. I now have a script to do this and will fix a couple of remaining cases by hand. 

While looking into this, I think I found a bug in the current version of [fix_nonadvective_mosaic.f90](https://github.com/COSIMA/topogtools/blob/master/fix_nonadvective_mosaic.f90). I've created a pull request. Would be great if you could have a look!

**Comment by micaeljtoliveira** [comment]
Reopening this, as it needs changes to https://github.com/COSIMA/025deg_jra55_ryf and https://github.com/COSIMA/025deg_jra55_iaf, plust some further testing.

**Comment by micaeljtoliveira** [comment]
Some updates regarding this issue. After successfully generating the updated topography and fixing the non-advective cells, I've regenerated the regriding weights used to couple the atmosphere with the ocean/ice models and updated the mask table. All the new files can be found here: `/g/data/ik11/inputs/access-om2/input_20220919_025deg_topog`. 

There is now a new branch named `update_antarctic_topo` in both https://github.com/COSIMA/025deg_jra55_ryf and https://github.com/COSIMA/025deg_jra55_iaf using the updated inputs. I've done a quick check by running the `025deg_jra55_iaf` configuration for one month with daily output. As expected, when comparing with a similar run with the old topography, changes in the outputs are only observed in the antarctic region, and they become larger with time. All the differences look reasonable to me, but it would be good if people could test the new files and report any feedback here.

**Comment by aekiss** [comment]
@ofa001, @davebi, @martindix we'd be interested in hearing whether this new topography 
`/g/data/ik11/inputs/access-om2/input_20220919_025deg_topog`
works better for ACCESS-CM2-025 than the previous one (TOPO5 `/g/data/ik11/inputs/access-om2/input_20211125_025deg_topog/mom_025deg/topog.nc`; see https://github.com/COSIMA/access-om2/issues/158)

**Comment by aekiss** [comment]
Note that there are changes to the land mask and processor layout.

**Comment by ofa001** [comment]
Hi @aekiss noting that @MartinDix is starting a new 0.25 coupled run to try out  new GM values this might be a good time to test the topography as well though he was going to start part way through the existing run, is that correct @MartinDiX @AndyHoggANU

**Comment by MartinDix** [comment]
The UM uses fractional land and a land mask that includes all points where the land fraction is non-zero. Process is to average the MOM land mask to the UM grid using the ESMF weights and set any grid boxes with land fraction < 0.01 to all ocean. This was an arbitrary limit and the Met Office don't use a limit at all so have some tiny land fractions. This map shows change in land fraction with the new MOM mask, red more land, blue less land.

![sftlf_diff](https://user-images.githubusercontent.com/1627802/194192249-c79239ea-f887-4ab2-95ce-cf9f44ab990e.png)

The change in land sea mask shows some extra islands that I'd never heard of which have land fraction just > 0.01 on the N96 grid. Peter I island at approx 70S 90W and the Balleny Islands at 66S, 164E. Google maps doesn't even know the name of these! https://www.google.com/maps/@-66.9249036,163.6697566,7.37z. Bing maps does name them.

![lmask_diff](https://user-images.githubusercontent.com/1627802/194192502-20bb1769-389c-40a8-ba94-1c108b2c5eb1.png)

**Comment by ofa001** [comment]
Thanks @MartinDix  Balleny Islands I have heard of Islands but not sure I know of Peter Is.  Glad we know have matching grid set ups and can do a test with the new ocean topography.

**Comment by aekiss** [comment]
@MartinDix, @ofa001, @davebi - just wondering if you've done a test run with this corrected 0.25deg bathymetry? I'd like to make this the default for ACCESS-OM2-025 but I want to know if it's suitable for ACCESS-CM2-0.25 first.

**Comment by MartinDix** [comment]
Just started a new run with this bathymetry.

**Comment by aekiss** [comment]
Great! I'm interested to see how that goes.

**Comment by MartinDix** [comment]
Some global means statistics from run in progress, https://accessdev.nci.org.au/p66/mrd599/access-cm2/control025/

Original run had a crash around Antarctica about every 20 years on average. No problems in the new run yet.

**Comment by aekiss** [comment]
Thanks @Martin, glad to hear it's more stable now.

Those plots mostly look good, but these things jumped out for me:

The Baltic is still heading very low (as with the previous topo) - was the initial condition based on obs (eg WOA)?
![](https://accessdev.nci.org.au/p66/mrd599/access-cm2/control025/baltic_sss.png)

cf. [ACCESS-OM2-025 test runs](https://github.com/COSIMA/access-om2/issues/158#issuecomment-982228479)
![](https://user-images.githubusercontent.com/26753100/143976308-ac88bca7-4380-44e4-9c00-23d8485b2ea0.png)

Min SSS is taking a weird plunge - hope it levels off!
![](https://accessdev.nci.org.au/p66/mrd599/access-cm2/control025/sss_min.png)

Sept SH SIA has dropped slightly, might be a bit below obs now; SIV also has the same dip
![](https://accessdev.nci.org.au/p66/mrd599/access-cm2/control025/ice_area_September_SH.png)
![](https://accessdev.nci.org.au/p66/mrd599/access-cm2/control025/ice_vol_September_SH.png)

**Comment by MartinDix** [comment]
The mask has some isolated ocean points near the Antarctic Peninsula and one of these is where the salinity goes to zero in year 24.

Image above at https://github.com/COSIMA/access-om2/issues/265#issuecomment-1231159693 shows these as connected but they're isolated in `/g/data/ik11/inputs/access-om2/input_20220919_025deg_topog/mom_025deg/ocean_mask.nc`.

Did something happen when removing the non-advective points?

![topog](https://user-images.githubusercontent.com/1627802/229392338-1ce3df59-69aa-4b9f-9428-fe929bf20e60.png)


![mask_20220919](https://user-images.githubusercontent.com/1627802/229392384-02cbfa6d-1489-4e2b-b55f-401da9379dff.png)

**Comment by ofa001** [comment]
That area you have circled in the West Antarctic @MartinDix looks concerning, its probably topography under an ice shelf rather the coastline itself. We proably need to eliminate it. The runs not going to be happy if salinity reaches zero.

**Comment by micaeljtoliveira** [comment]
> Did something happen when removing the non-advective points?

I think I didn't realize that the fixing of non-advective cells could create kind of isolated points. In the workflow I used, isolated cells are only removed **before** fixing the non-advective cells.

**Comment by ofa001** [comment]
Hi @micaeljtoliveira,  that means it might need a second pass to remove any new isolated point.

**Comment by micaeljtoliveira** [comment]
I'll try to get an updated topography and masks ASAP.

**Comment by aekiss** [comment]
thanks @micaeljtoliveira

**Comment by micaeljtoliveira** [comment]
@MartinDix I've finally updated the inputs with a new version of the topography that should have those isolated points removed. The new inputs are in `/g/data/ik11/inputs/access-om2/input_20230515_025deg_topog`. Would be great to have this tested at some point.

(see the following PR for a plot of the new topography vs old: https://github.com/COSIMA/make_025deg_topo/pull/2)

**Comment by aekiss** [comment]
@wghuneke has a test run been done with this new topography and land mask? If it works well it would be good to make this the default in the standard configs.

**Comment by wghuneke** [comment]
Yes, the new bathymetry works well for me, no crashes anymore. I'd support making this the new default product.

**Comment by ofa001** [comment]
Thats good news Willma, we can start using  the updated  bathymetry for new 0.25 runs at CSIRO

**Comment by micaeljtoliveira** [comment]
I think this can be closed now :tada:

**Comment by aekiss** [comment]
Closed - 0.25° JRA55 configurations (RYF and IAF, master and master+bgc) now all use `/g/data/ik11/inputs/access-om2/input_20230515_025deg_topog`.
