### ISSUE TITLE
Incorrect initial conditions for most configurations

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/access-om2#39]
The `input/mom_1deg/ocean_temp_salt.res.nc` file is the old Levitus initial conditions.

Now we're using the regridded WOA13 files here:

```md5sum /g/data1/ua8/MOM/initial_conditions/WOA/10/ocean_temp_salt.res.nc
1b3c43840432aac5a0d8f9b998443c7b  /g/data1/ua8/MOM/initial_conditions/WOA/10/ocean_temp_salt.res.nc
```

Andy has an earlier version of this file, so though his md5sum is not the same, I have checked and the data inside matches.

I'm assuming all the other initial conditions files need to change also

**Comment by nicjhan** [comment]
I'm guessing that there could be problems with the other resolutions too.

**Comment by aidanheerdegen** [comment]
I'd imagine so.

**Comment by nichannah** [comment]
@aidanheerdegen do you know if this is still the case? If so, do you know where the correct files are?

**Comment by aekiss** [comment]
This is a problem for all the input directories other than
```
/short/public/access-om2/input_236a3011/mom_1deg/ocean_temp_salt.res.nc
/short/public/access-om2/input_236a3011/mom_025deg/ocean_temp_salt.res.nc
```
So the release candidates `/short/public/access-om2/input_rc/*/ocean_temp_salt.res.nc` need fixing.

The [standard configs](https://github.com/COSIMA/access-om2/tree/master/control) currently use these:
```
01deg_jra55_iaf/config.yaml:input: /short/public/access-om2/input_08022019/common_01deg_jra55
01deg_jra55_ryf/config.yaml:input: /short/public/access-om2/input_08022019/common_01deg_jra55
025deg_core2_nyf/config.yaml:input: /short/public/access-om2/input_337f4505/common_025deg_core
025deg_jra55_iaf/config.yaml:input: /short/public/access-om2/input_236a3011/common_025deg_jra55
025deg_jra55_ryf/config.yaml:input: /short/public/access-om2/input_337f4505/common_025deg_jra55
1deg_core_nyf/config.yaml:input: /short/public/access-om2/input_337f4505/common_1deg_core
1deg_jra55_iaf/config.yaml:input: /short/public/access-om2/input_236a3011/common_1deg_jra55
1deg_jra55_ryf/config.yaml:input: /short/public/access-om2/input_236a3011/common_1deg_jra55
minimal_01deg_jra55_iaf/config.yaml:input: /short/public/access-om2/input_08022019/common_01deg_jra55
minimal_01deg_jra55_ryf/config.yaml:input: /short/public/access-om2/input_08022019/common_01deg_jra55
```
So we need to fix most of these, i.e. fix the release candidate and link to that when it's ready.

Following https://github.com/COSIMA/access-om2/issues/159 we are back to using `input_236a3011` for 1 deg IAF and RYF and for 0.25 deg IAF, so those 3 are the only ones with the correct initial condition.

----------------

Details for reference:
At 1 deg:
```
for d in /short/public/access-om2/*/mom_1deg/ocean_temp_salt.res.nc; do diff -s $d /g/data1/ua8/MOM/initial_conditions/WOA/10_KDS50/ocean_temp_salt.res.nc; done
Files /short/public/access-om2/input_236a3011/mom_1deg/ocean_temp_salt.res.nc and /g/data1/ua8/MOM/initial_conditions/WOA/10_KDS50/ocean_temp_salt.res.nc are identical
```
but all the others differ, including the release candidate `/short/public/access-om2/input_rc/mom_1deg/ocean_temp_salt.res.nc`

At 0.25 deg:
```
for d in /short/public/access-om2/*/mom_025deg/ocean_temp_salt.res.nc; do diff -s $d /g/data1/ua8/MOM/initial_conditions/WOA/025_KDS50/ocean_temp_salt.res.nc; done
Files /short/public/access-om2/input_236a3011/mom_025deg/ocean_temp_salt.res.nc and /g/data1/ua8/MOM/initial_conditions/WOA/025_KDS50/ocean_temp_salt.res.nc are identical
```
but all the others differ, including the release candidate `/short/public/access-om2/input_rc/mom_025deg/ocean_temp_salt.res.nc`

At 0.1deg:
```
for d in /short/public/access-om2/*/mom_01deg/ocean_temp_salt.res.nc; do diff -s $d /g/data1/ua8/MOM/initial_conditions/WOA/01/ocean_temp_salt.res.nc; done
```
all files differ, including the release candidate `/short/public/access-om2/input_rc/mom_01deg/ocean_temp_salt.res.nc`

**Comment by aekiss** [comment]
Also, we are now using conservative temperature as the prognostic variable for all configurations, but the initial condition is potential temperature. Is this cause for concern? Or unavoidable?

**Comment by aekiss** [comment]
The release candidates `/short/public/access-om2/input_rc/*/ocean_temp_salt.res.nc` have now been fixed (I think!):
```
cp /g/data1/ua8/MOM/initial_conditions/WOA/01/ocean_temp_salt.res.nc /short/public/access-om2/input_rc/mom_01deg/
cp /g/data1/ua8/MOM/initial_conditions/WOA/025_KDS50/ocean_temp_salt.res.nc /short/public/access-om2/input_rc/mom_025deg/
cp /g/data1/ua8/MOM/initial_conditions/WOA/10_KDS50/ocean_temp_salt.res.nc /short/public/access-om2/input_rc/mom_1deg/
```
I hope these are the correct files - @aidanheerdegen can you confirm?

**Comment by aidanheerdegen** [comment]
Yes they are the WOA initial conditions files I created.

**Comment by nichannah** [comment]
Is this still an issue?

**Comment by aekiss** [comment]
closing - fixed in `ak-dev` branch for all configs, which all use `/g/data/ik11/inputs/access-om2/input_rc` --- see `/g/data/ik11/inputs/access-om2/input_rc/README.txt`

**Comment by aekiss** [comment]
For future reference:

The [GMD2020](https://doi.org/10.5194/gmd-13-401-2020) 1deg and 0.25deg configurations
https://github.com/COSIMA/1deg_jra55_iaf/releases/tag/1.0
https://github.com/COSIMA/025deg_jra55_iaf/releases/tag/1.0
used `input_236a3011` which is WOA, so they're fine.

The GMD2020 0.1deg config
https://github.com/COSIMA/01deg_jra55_iaf/releases/tag/1.0
used an initial condition from this 40-year RYF spinup
https://github.com/COSIMA/01deg_jra55_ryf/blob/01deg_jra55v13_ryf8485_spinup6/config.yaml
which used 
/g/data/ik11/inputs/access-om2/input_38570c62/mom_01deg/ocean_temp_salt.res.nc
which differs from the WOA IC
/g/data/ua8/MOM/initial_conditions/WOA/01/ocean_temp_salt.res.nc 
but only with a relative error of 5.9e-15 for salt and 3.1e-14 for temp, close to the double-precision roundoff.
So we can safely conclude that this starts from WOA also.
