### ISSUE TITLE
Scaling and performance accounting and documentation for the 0.1 degree configuration

### ISSUE THREAD

**Issue by nichannah** [COSIMA/access-om2#45]
This needs to be documented for NCI computer time applications and other reasons. 

High priority.

**Comment by aekiss** [comment]
We could provide links to .csv tables auto-generated by https://github.com/aekiss/run_summary
e.g. see `/g/data3/hh5/tmp/cosima/access-om2-run-summaries`

Does this cover all the info required?

**Comment by aekiss** [comment]
As of commits https://github.com/aekiss/run_summary/commit/fd5f4d68c10b58229b30d572dee24dd8ad59d7de and https://github.com/aekiss/run_summary/commit/6252da6b2be2a7596a4edf354bbff6ec87edb1ee run_summary now collects MOM and CICE timing info.

I've added a table of typical resource requirements in the wiki: https://github.com/COSIMA/access-om2/wiki/Technical-documentation#Scaling-and-performance

Is there anything else left to do?
