### ISSUE TITLE
Tool to create alternate resolutions based on an existing experiment

### ISSUE THREAD

**Issue by nichannah** [COSIMA/access-om2#69]
Trevor and his student Veronica need a 1/3 deg resolution ocean and ice model to test their HRM mixing parameterisation. 

This issue proposes a generalised tool that will make it possible to create a new resolution by refining an existing grid and inputs. For example to make a 1/3 deg bathymetry we take the 1 deg topog.nc and replace each cell with 9 equal cells.

The remapping weights will need to be regenerated from scratch using the new grid. 

Does this sound feasible? @russfiedler I think you spoke to Trevor about this, does it sound reasonable to you? Can you think of any big difficulties along the way? Thanks

**Comment by aekiss** [comment]
Is there a reason they don't want to use the 1/4 deg config?

**Comment by russfiedler** [comment]
They need exact alignment of tracer & velocity cell centres and 
advective velocities I think. You get this by refining by 3 but not by 4.

**Comment by nicjhan** [comment]
@VLIUNSW do you have anything to add as to why we can't use the 1/4 deg for this?

**Comment by russfiedler** [comment]
Should be fairly straight forward. Just need to be careful at the tripolar join I think. You'd need to recreate the land mask for the 0.25 grid anyway.

**Comment by VLIUNSW** [comment]
Russ was right - we need the coarse resolution to be 3 times the fine resolution.

Also, we need the one 1 degree and 1/3 degree to have the same bathymetry. Hopefully, using the same bathymetry will resolve the problems we had at some boundary areas. Boundary areas are crucial.

Thank you!

**Comment by nicjhan** [comment]
Altogether there are around 30 files that will need to be refined. Most will be fairly generic apart from dealing with the various netcdf file (non)conventions. Creating the mosaic grid and the remapping weights will be more time consuming. 

I'm estimating that this task will take about a week to do and a week for tests and runs. As with anything to do with models we also need to expect problems which could double the estimate. So 2-4 weeks of work all up.

**Comment by cdelav3** [comment]
Thank you Nic and Russ to help us with this.

The 2-3 weeks work estimate to have the 1/3 deg resolution (with 1 deg effective bathymetric resolution) seems realistic. I hope this can be done.

Recall that, _if ever_ this was faster/easier, we would also be happy to run the 1/4 deg resolution with 3/4 deg effective bathymetric resolution. This would obviate the need to create a new 1/3 deg grid and associated forcing fields, but it would demand to create a new 3/4 deg bathymetry.

Thanks!
Casimir

**Comment by nichannah** [comment]
This issue is getting old. We can re-open if/when necessary.
